// Code generated by GoForge. DO NOT EDIT.

package jobs

import (
	"fmt"

	"github.com/ShanilKoshitha/goforge/job"
)

// NewRegistry explicitly wires every application-owned job handler.
func NewRegistry(dependencies Dependencies) (*job.Registry, error) {
	registry := job.NewRegistry()
	_ = dependencies
	handlerSendWelcome := SendWelcomeHandler{Dependencies: dependencies}
	if err := job.Register(registry, SendWelcomeDefinition, handlerSendWelcome.Handle); err != nil {
		return nil, fmt.Errorf("register send_welcome.v1: %w", err)
	}
	return registry, nil
}
