// Code generated by GoForge. DO NOT EDIT.

package routes

import (
	"database/sql"

	"github.com/ShanilKoshitha/goforge/httpx"
	"github.com/ShanilKoshitha/goforge/session"
	"github.com/ShanilKoshitha/goforge/view"
	"github.com/ShanilKoshitha/goforge/web"

	issueresource "example.com/format6/internal/resources/issue"
)

func registerResources(router *httpx.Router, renderer *view.Engine, db *sql.DB, manager *session.Manager, requireAuth, requireWebAuth httpx.Middleware) {
	browserRoute := func(handler httpx.Handler) httpx.Handler {
		return web.Sessions(manager)(web.CSRF()(requireWebAuth(handler)))
	}
	issueRepository := issueresource.NewPostgresRepository(db)
	issueController := issueresource.NewController(issueRepository)
	issueWebController := issueresource.NewWebController(issueRepository, renderer)
	router.Named("issues.index", "GET", "/issues", requireAuth(issueController.Index))
	router.Named("issues.create", "POST", "/issues", requireAuth(issueController.Create))
	router.Named("issues.show", "GET", "/issues/{id}", requireAuth(issueController.Show))
	router.Named("issues.update", "PUT", "/issues/{id}", requireAuth(issueController.Update))
	router.Named("issues.delete", "DELETE", "/issues/{id}", requireAuth(issueController.Delete))
	router.Named("web.issues.index", "GET", "/app/issues", browserRoute(issueWebController.Index))
	router.Named("web.issues.new", "GET", "/app/issues/new", browserRoute(issueWebController.New))
	router.Named("web.issues.create", "POST", "/app/issues", browserRoute(issueWebController.Create))
	router.Named("web.issues.show", "GET", "/app/issues/{id}", browserRoute(issueWebController.Show))
	router.Named("web.issues.edit", "GET", "/app/issues/{id}/edit", browserRoute(issueWebController.Edit))
	router.Named("web.issues.update", "PUT", "/app/issues/{id}", browserRoute(issueWebController.Update))
	router.Named("web.issues.delete", "DELETE", "/app/issues/{id}", browserRoute(issueWebController.Delete))
}
