// Code generated by GoForge. DO NOT EDIT.

package models

import (
	context "context"
	orm "github.com/ShanilKoshitha/goforge/orm"
	time "time"
)

// Store keeps execution explicit. Both *sql.DB and *sql.Tx implement
// orm.Executor, and callers can always use either value directly.
type Store struct {
	Executor orm.Executor
}

func NewStore(executor orm.Executor) Store {
	return Store{Executor: executor}
}

var IssueMapper = orm.MustMapper[Issue](
	[]string{
		"id",
		"user_id",
		"name",
		"created_at",
		"updated_at",
		"version",
	},
	func(row orm.RowScanner) (Issue, error) {
		var model Issue
		err := row.Scan(
			&model.ID,
			&model.UserID,
			&model.Name,
			&model.CreatedAt,
			&model.UpdatedAt,
			&model.Version,
		)
		return model, err
	},
)

var IssueTable = orm.MustTable("issues", IssueMapper)

var IssueColumns = struct {
	ID        orm.Column[Issue, int64]
	UserID    orm.Column[Issue, int64]
	Name      orm.Column[Issue, string]
	CreatedAt orm.Column[Issue, time.Time]
	UpdatedAt orm.Column[Issue, time.Time]
	Version   orm.Column[Issue, int64]
}{
	ID:        orm.MustColumn[Issue, int64](IssueTable, "id"),
	UserID:    orm.MustColumn[Issue, int64](IssueTable, "user_id"),
	Name:      orm.MustColumn[Issue, string](IssueTable, "name"),
	CreatedAt: orm.MustColumn[Issue, time.Time](IssueTable, "created_at"),
	UpdatedAt: orm.MustColumn[Issue, time.Time](IssueTable, "updated_at"),
	Version:   orm.MustColumn[Issue, int64](IssueTable, "version"),
}

// IssueCreateInput exposes writable fields only. Fields backed by a
// database default or SQL NULL use orm.Field: zero means omit, orm.Null means
// NULL, and orm.Value supplies a concrete value.
type IssueCreateInput struct {
	Name string
}

func (input IssueCreateInput) Assignments() []orm.Assignment[Issue] {
	return []orm.Assignment[Issue]{
		IssueColumns.Name.Set(input.Name),
	}
}

// IssueChanges is partial: each zero-value orm.Field is omitted, while
// orm.Null and orm.Value preserve explicit NULL and value assignments.
type IssueChanges struct {
	Name orm.Field[string]
}

func (changes IssueChanges) Assignments() []orm.Assignment[Issue] {
	return []orm.Assignment[Issue]{
		IssueColumns.Name.From(changes.Name),
	}
}

// IssueQuery binds the model's typed builders to one explicit executor.
// Additional mutation assignments are intentionally accepted so repositories
// can set protected ownership columns through IssueColumns.
type IssueQuery struct {
	Executor orm.Executor
}

func (store Store) Issues() IssueQuery {
	return IssueQuery{Executor: store.Executor}
}

func (query IssueQuery) Select() orm.SelectBuilder[Issue] {
	return orm.Select(IssueTable)
}

func (query IssueQuery) Create(input IssueCreateInput, additional ...orm.Assignment[Issue]) orm.InsertBuilder[Issue] {
	assignments := input.Assignments()
	assignments = append(assignments, additional...)
	return orm.Insert(IssueTable).Values(assignments...)
}

func (query IssueQuery) Update(changes IssueChanges, additional ...orm.Assignment[Issue]) orm.UpdateBuilder[Issue] {
	assignments := changes.Assignments()
	assignments = append(assignments, additional...)
	return orm.Update(IssueTable).Set(assignments...)
}

func (query IssueQuery) Delete() orm.DeleteBuilder[Issue] {
	return orm.Delete(IssueTable)
}

// IssueRelations contains the default typed relationship descriptors.
// The exported descriptor factories accept RelationOptions when a caller needs
// an explicit parameter budget instead of the PostgreSQL default.
func IssueOwnerRelation(options orm.RelationOptions) orm.BelongsTo[Issue, User, int64] {
	return orm.MustBelongsTo(
		IssueTable, UserTable,
		IssueColumns.UserID, UserColumns.ID,
		func(parent Issue) (int64, bool) {
			return parent.UserID, true
		},
		func(target User) (int64, bool) {
			return target.ID, true
		},
		func(parent *Issue, related *User) {
			parent.Owner = related
		},
		options,
	)
}

var IssueRelations = struct {
	Owner orm.BelongsTo[Issue, User, int64]
}{
	Owner: IssueOwnerRelation(orm.RelationOptions{}),
}

// LoadOwner loads Owner through the caller-provided target scope.
// The scope remains visible and may include predicates and ordering.
func (query IssueQuery) LoadOwner(ctx context.Context, parents []Issue, scope orm.SelectBuilder[User]) ([]Issue, error) {
	return IssueRelations.Owner.Load(ctx, query.Executor, parents, scope)
}

var UserMapper = orm.MustMapper[User](
	[]string{
		"id",
		"name",
		"email",
		"password_hash",
		"created_at",
		"updated_at",
	},
	func(row orm.RowScanner) (User, error) {
		var model User
		err := row.Scan(
			&model.ID,
			&model.Name,
			&model.Email,
			&model.PasswordHash,
			&model.CreatedAt,
			&model.UpdatedAt,
		)
		return model, err
	},
)

var UserTable = orm.MustTable("users", UserMapper)

var UserColumns = struct {
	ID           orm.Column[User, int64]
	Name         orm.Column[User, string]
	Email        orm.Column[User, string]
	PasswordHash orm.Column[User, string]
	CreatedAt    orm.Column[User, time.Time]
	UpdatedAt    orm.Column[User, time.Time]
}{
	ID:           orm.MustColumn[User, int64](UserTable, "id"),
	Name:         orm.MustColumn[User, string](UserTable, "name"),
	Email:        orm.MustColumn[User, string](UserTable, "email"),
	PasswordHash: orm.MustColumn[User, string](UserTable, "password_hash"),
	CreatedAt:    orm.MustColumn[User, time.Time](UserTable, "created_at"),
	UpdatedAt:    orm.MustColumn[User, time.Time](UserTable, "updated_at"),
}

// UserCreateInput exposes writable fields only. Fields backed by a
// database default or SQL NULL use orm.Field: zero means omit, orm.Null means
// NULL, and orm.Value supplies a concrete value.
type UserCreateInput struct {
	Name  string
	Email string
}

func (input UserCreateInput) Assignments() []orm.Assignment[User] {
	return []orm.Assignment[User]{
		UserColumns.Name.Set(input.Name),
		UserColumns.Email.Set(input.Email),
	}
}

// UserChanges is partial: each zero-value orm.Field is omitted, while
// orm.Null and orm.Value preserve explicit NULL and value assignments.
type UserChanges struct {
	Name  orm.Field[string]
	Email orm.Field[string]
}

func (changes UserChanges) Assignments() []orm.Assignment[User] {
	return []orm.Assignment[User]{
		UserColumns.Name.From(changes.Name),
		UserColumns.Email.From(changes.Email),
	}
}

// UserQuery binds the model's typed builders to one explicit executor.
// Additional mutation assignments are intentionally accepted so repositories
// can set protected ownership columns through UserColumns.
type UserQuery struct {
	Executor orm.Executor
}

func (store Store) Users() UserQuery {
	return UserQuery{Executor: store.Executor}
}

func (query UserQuery) Select() orm.SelectBuilder[User] {
	return orm.Select(UserTable)
}

func (query UserQuery) Create(input UserCreateInput, additional ...orm.Assignment[User]) orm.InsertBuilder[User] {
	assignments := input.Assignments()
	assignments = append(assignments, additional...)
	return orm.Insert(UserTable).Values(assignments...)
}

func (query UserQuery) Update(changes UserChanges, additional ...orm.Assignment[User]) orm.UpdateBuilder[User] {
	assignments := changes.Assignments()
	assignments = append(assignments, additional...)
	return orm.Update(UserTable).Set(assignments...)
}

func (query UserQuery) Delete() orm.DeleteBuilder[User] {
	return orm.Delete(UserTable)
}
