package httpx

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"
	"net/url"
)

const defaultMaxBodyBytes int64 = 1 << 20

// Context holds request-local state. Like an http.ResponseWriter, it must not be
// used after the handler returns or written from concurrent goroutines.
type Context struct {
	Response       http.ResponseWriter
	Request        *http.Request
	values         map[string]any
	routeErr       error
	routeName      string
	routePattern   string
	requestID      string
	response       *statusWriter // Tracks writes even when middleware wraps Response.
	originalMethod string
	form           url.Values
	formErr        error
	formParsed     bool
	formBytes      int64
}

func newContext(response http.ResponseWriter, request *http.Request) *Context {
	tracker, compatible := newStatusWriter(response)
	return &Context{
		Response: compatible, Request: request, response: tracker,
		originalMethod: request.Method,
	}
}

// OriginalMethod returns the request method received by the router before
// middleware such as MethodOverride changes it.
func (ctx *Context) OriginalMethod() string {
	return ctx.originalMethod
}

func (ctx *Context) Param(name string) string {
	return ctx.Request.PathValue(name)
}

func (ctx *Context) Query(name string) string {
	return ctx.Request.URL.Query().Get(name)
}

// RouteName reports the explicit name of the matched route. It is empty for
// unnamed routes and requests that did not match a GoForge route.
func (ctx *Context) RouteName() string { return ctx.routeName }

// RoutePattern reports the low-cardinality application path pattern of the
// matched route. It never contains concrete path parameter values.
func (ctx *Context) RoutePattern() string { return ctx.routePattern }

// RequestID reports the identifier accepted or generated by RequestID
// middleware. It is empty when that middleware has not run.
func (ctx *Context) RequestID() string { return ctx.requestID }

func (ctx *Context) Set(name string, value any) {
	if ctx.values == nil {
		ctx.values = make(map[string]any)
	}
	ctx.values[name] = value
}

func (ctx *Context) Get(name string) (any, bool) {
	value, ok := ctx.values[name]
	return value, ok
}

func (ctx *Context) JSON(status int, value any) error {
	var body bytes.Buffer
	if err := json.NewEncoder(&body).Encode(value); err != nil {
		return fmt.Errorf("encode JSON response: %w", err)
	}
	ctx.Response.Header().Set("Content-Type", "application/json; charset=utf-8")
	ctx.Response.WriteHeader(status)
	if _, err := ctx.Response.Write(body.Bytes()); err != nil {
		return fmt.Errorf("write JSON response: %w", err)
	}
	return nil
}

func (ctx *Context) NoContent(status int) error {
	ctx.Response.WriteHeader(status)
	return nil
}

func (ctx *Context) Redirect(status int, location string) error {
	http.Redirect(ctx.Response, ctx.Request, location, status)
	return nil
}

// BindJSON requires an application/json Content-Type (parameters are allowed)
// and decodes one JSON value, rejecting unknown fields and bodies over 1 MiB.
func (ctx *Context) BindJSON(target any) error {
	return ctx.BindJSONLimit(target, defaultMaxBodyBytes)
}

// BindJSONLimit applies the same rules as BindJSON with a custom byte limit.
func (ctx *Context) BindJSONLimit(target any, maxBytes int64) error {
	if maxBytes <= 0 {
		return fmt.Errorf("JSON body limit must be positive")
	}
	mediaType, _, err := mime.ParseMediaType(ctx.Request.Header.Get("Content-Type"))
	if err != nil || mediaType != "application/json" {
		return NewHTTPError(http.StatusUnsupportedMediaType, "Content-Type must be application/json")
	}
	if ctx.Request.Body == nil {
		return NewHTTPError(http.StatusBadRequest, "request body is required")
	}
	ctx.Request.Body = http.MaxBytesReader(ctx.Response, ctx.Request.Body, maxBytes)
	decoder := json.NewDecoder(ctx.Request.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		var tooLarge *http.MaxBytesError
		if errors.As(err, &tooLarge) {
			return NewHTTPError(http.StatusRequestEntityTooLarge, "JSON body is too large").WithCause(err)
		}
		return NewHTTPError(http.StatusBadRequest, "invalid JSON body").WithCause(err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return NewHTTPError(http.StatusBadRequest, "request body must contain one JSON value")
	}
	return nil
}
