package cli

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// modelSchema is the generator's deterministic, source-derived description of
// application models. It deliberately contains data only: generation remains a
// separate concern and never needs runtime reflection.
type modelSchema struct {
	Models        []modelDefinition
	DeclaredNames []string
}

type modelDefinition struct {
	Name       string
	Table      string
	SourceFile string
	Fields     []modelField
	Relations  []modelRelation
}

type modelField struct {
	Name   string
	GoType string
	// GeneratedGoType is the equivalent type expression using stable import
	// names suitable for a separately generated Go file.
	GeneratedGoType string
	GoImportPath    string
	Column          string
	DBType          string
	Primary         bool
	Generated       bool
	Protected       bool
	Required        bool
	Nullable        bool
	Default         *string
	Indexed         bool
	Unique          bool
	Reference       *modelReference
	OnDelete        string
	SourceLine      int
	typeFamily      string
}

type modelReference struct {
	Model  string
	Field  string
	Table  string
	Column string
}

type modelRelation struct {
	Name             string
	Kind             string
	Target           string
	Pointer          bool
	ForeignKey       string
	References       string
	TargetKey        string
	JoinTable        string
	JoinForeignKey   string
	JoinReferenceKey string
	SourceLine       int
}

const (
	relationBelongsTo  = "belongs_to"
	relationHasOne     = "has_one"
	relationHasMany    = "has_many"
	relationManyToMany = "many_to_many"
)

var (
	databaseIdentifier  = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	sizedDatabaseType   = regexp.MustCompile(`^(?:varchar|character varying)\([1-9][0-9]{0,5}\)$`)
	numericDatabaseType = regexp.MustCompile(`^numeric\([1-9][0-9]{0,3}(?:,[0-9]{1,3})?\)$`)
	integerDefault      = regexp.MustCompile(`^[+-]?[0-9]+$`)
	decimalDefault      = regexp.MustCompile(`^[+-]?(?:[0-9]+\.[0-9]+|[0-9]+)$`)
	quotedDefault       = regexp.MustCompile(`^'(?:[^']|'')*'$`)
)

type parsedModel struct {
	definition modelDefinition
	file       *parsedModelFile
}

type parsedModelFile struct {
	name    string
	fset    *token.FileSet
	file    *ast.File
	imports map[string]string
}

type scalarType struct {
	expression ast.Expr
	file       *parsedModelFile
}

// parseModelSchema parses all non-test Go files immediately inside directory.
// Files and returned models are sorted by name; fields and relations retain
// their declaration order within each model.
func parseModelSchema(directory string) (modelSchema, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return modelSchema{}, fmt.Errorf("read model directory: %w", err)
	}
	var names []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
			names = append(names, entry.Name())
		}
	}
	sort.Strings(names)
	if len(names) == 0 {
		return modelSchema{}, fmt.Errorf("model directory %s contains no Go source files", filepath.ToSlash(directory))
	}

	files := make([]*parsedModelFile, 0, len(names))
	for _, name := range names {
		filename := filepath.Join(directory, name)
		source, err := os.ReadFile(filename)
		if err != nil {
			return modelSchema{}, fmt.Errorf("read model source %s: %w", filepath.ToSlash(filename), err)
		}
		if bytes.HasPrefix(source, []byte("// Code generated by GoForge. DO NOT EDIT.")) {
			continue
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, filename, source, parser.ParseComments|parser.AllErrors)
		if err != nil {
			return modelSchema{}, fmt.Errorf("parse model source %s: %w", filepath.ToSlash(filename), err)
		}
		if constrainedModelFilename(name) || hasBuildConstraint(file) {
			return modelSchema{}, schemaError(name, 1, "model files cannot use build constraints")
		}
		if ast.IsGenerated(file) {
			continue
		}
		if file.Name.Name != "models" {
			return modelSchema{}, schemaError(name, fset.Position(file.Package).Line, "package must be models, got %s", file.Name.Name)
		}
		imports, err := modelImports(name, fset, file)
		if err != nil {
			return modelSchema{}, err
		}
		files = append(files, &parsedModelFile{name: name, fset: fset, file: file, imports: imports})
	}
	declaredNames := make(map[string]struct{})
	for _, file := range files {
		for _, declaration := range file.file.Decls {
			switch item := declaration.(type) {
			case *ast.FuncDecl:
				if item.Recv == nil {
					declaredNames[item.Name.Name] = struct{}{}
				}
			case *ast.GenDecl:
				for _, rawSpec := range item.Specs {
					switch spec := rawSpec.(type) {
					case *ast.TypeSpec:
						declaredNames[spec.Name.Name] = struct{}{}
					case *ast.ValueSpec:
						for _, name := range spec.Names {
							declaredNames[name.Name] = struct{}{}
						}
					}
				}
			}
		}
	}

	scalars := make(map[string]scalarType)
	for _, file := range files {
		for _, declaration := range file.file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}
			for _, item := range general.Specs {
				spec := item.(*ast.TypeSpec)
				if _, ok := spec.Type.(*ast.StructType); ok {
					continue
				}
				if _, exists := scalars[spec.Name.Name]; exists {
					return modelSchema{}, schemaError(file.name, file.fset.Position(spec.Pos()).Line, "duplicate type %s", spec.Name.Name)
				}
				scalars[spec.Name.Name] = scalarType{expression: spec.Type, file: file}
			}
		}
	}

	var parsed []parsedModel
	seenModels := make(map[string]string)
	seenTables := make(map[string]string)
	for _, file := range files {
		for _, declaration := range file.file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}
			for _, item := range general.Specs {
				spec := item.(*ast.TypeSpec)
				structure, ok := spec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				line := file.fset.Position(spec.Pos()).Line
				if spec.TypeParams != nil {
					return modelSchema{}, schemaError(file.name, line, "model %s cannot be generic", spec.Name.Name)
				}
				if !ast.IsExported(spec.Name.Name) {
					return modelSchema{}, schemaError(file.name, line, "model %s must be exported", spec.Name.Name)
				}
				if scalar, exists := scalars[spec.Name.Name]; exists {
					return modelSchema{}, schemaError(file.name, line, "model %s conflicts with scalar type in %s", spec.Name.Name, scalar.file.name)
				}
				if previous, exists := seenModels[spec.Name.Name]; exists {
					return modelSchema{}, schemaError(file.name, line, "duplicate model %s (first declared in %s)", spec.Name.Name, previous)
				}
				definition, err := parseModelDefinition(file, spec.Name.Name, structure, scalars)
				if err != nil {
					return modelSchema{}, err
				}
				if previous, exists := seenTables[definition.Table]; exists {
					return modelSchema{}, schemaError(file.name, line, "duplicate table %s used by %s and %s", definition.Table, previous, definition.Name)
				}
				seenModels[definition.Name] = file.name
				seenTables[definition.Table] = definition.Name
				parsed = append(parsed, parsedModel{definition: definition, file: file})
			}
		}
	}
	if len(parsed) == 0 {
		return modelSchema{}, fmt.Errorf("model directory %s declares no struct models", filepath.ToSlash(directory))
	}
	sort.Slice(parsed, func(i, j int) bool { return parsed[i].definition.Name < parsed[j].definition.Name })

	models := make(map[string]*modelDefinition, len(parsed))
	for index := range parsed {
		models[parsed[index].definition.Name] = &parsed[index].definition
	}
	for index := range parsed {
		if err := validateModelLinks(&parsed[index].definition, models, parsed[index].file.name); err != nil {
			return modelSchema{}, err
		}
	}
	if err := validateGeneratedDatabaseNames(parsed); err != nil {
		return modelSchema{}, err
	}
	if err := rejectReferenceCycles(parsed); err != nil {
		return modelSchema{}, err
	}

	result := modelSchema{Models: make([]modelDefinition, len(parsed)), DeclaredNames: make([]string, 0, len(declaredNames))}
	for index := range parsed {
		result.Models[index] = parsed[index].definition
	}
	for name := range declaredNames {
		result.DeclaredNames = append(result.DeclaredNames, name)
	}
	sort.Strings(result.DeclaredNames)
	return result, nil
}

func modelImports(filename string, fset *token.FileSet, file *ast.File) (map[string]string, error) {
	imports := make(map[string]string)
	for _, item := range file.Imports {
		importPath, err := strconv.Unquote(item.Path.Value)
		if err != nil {
			return nil, schemaError(filename, fset.Position(item.Pos()).Line, "invalid import path: %v", err)
		}
		alias := path.Base(importPath)
		if item.Name != nil {
			alias = item.Name.Name
		}
		if alias == "." {
			return nil, schemaError(filename, fset.Position(item.Pos()).Line, "dot imports cannot be resolved by the model generator")
		}
		if alias == "_" {
			continue
		}
		if previous, exists := imports[alias]; exists && previous != importPath {
			return nil, schemaError(filename, fset.Position(item.Pos()).Line, "import alias %s is ambiguous", alias)
		}
		imports[alias] = importPath
	}
	return imports, nil
}

func parseModelDefinition(file *parsedModelFile, name string, structure *ast.StructType, scalars map[string]scalarType) (modelDefinition, error) {
	tableBase, err := snake(name)
	if err != nil {
		return modelDefinition{}, schemaError(file.name, file.fset.Position(structure.Pos()).Line, "derive table for %s: %v", name, err)
	}
	derivedTable := pluralize(tableBase)
	if !safeIdentifier(derivedTable) {
		return modelDefinition{}, schemaError(file.name, file.fset.Position(structure.Pos()).Line, "model %s derives unsafe table name %q", name, derivedTable)
	}
	definition := modelDefinition{Name: name, Table: derivedTable, SourceFile: file.name}
	columns := make(map[string]string)
	fieldNames := make(map[string]struct{})
	primaryCount := 0
	tableDeclared := false
	for _, field := range structure.Fields.List {
		line := file.fset.Position(field.Pos()).Line
		if len(field.Names) == 0 {
			return modelDefinition{}, schemaError(file.name, line, "model %s cannot contain embedded fields", name)
		}
		if len(field.Names) != 1 {
			return modelDefinition{}, schemaError(file.name, line, "model fields must be declared one name per line")
		}
		fieldName := field.Names[0].Name
		forgeTag, dbTag, err := modelFieldTags(field)
		if err != nil {
			return modelDefinition{}, schemaError(file.name, line, "field %s: %v", fieldName, err)
		}
		options, err := parseForgeOptions(forgeTag)
		if err != nil {
			return modelDefinition{}, schemaError(file.name, line, "field %s: %v", fieldName, err)
		}
		if fieldName == "_" {
			if tableDeclared || len(options.flags) != 0 || len(options.values) != 1 || options.values["table"] == "" || dbTag != "" {
				return modelDefinition{}, schemaError(file.name, line, "model metadata must be `_ struct{} `forge:\"table=table_name\"``")
			}
			metadataType, ok := field.Type.(*ast.StructType)
			if !ok || len(metadataType.Fields.List) != 0 {
				return modelDefinition{}, schemaError(file.name, line, "model table metadata must use struct{}")
			}
			if !safeIdentifier(options.values["table"]) {
				return modelDefinition{}, schemaError(file.name, line, "unsafe table name %q", options.values["table"])
			}
			definition.Table = options.values["table"]
			tableDeclared = true
			continue
		}
		if !ast.IsExported(fieldName) {
			return modelDefinition{}, schemaError(file.name, line, "field %s must be exported", fieldName)
		}
		if _, exists := fieldNames[fieldName]; exists {
			return modelDefinition{}, schemaError(file.name, line, "duplicate field %s", fieldName)
		}
		fieldNames[fieldName] = struct{}{}
		if options.flags["ignore"] {
			if len(options.flags) != 1 || len(options.values) != 0 || dbTag != "" {
				return modelDefinition{}, schemaError(file.name, line, "ignore cannot be combined with persistence metadata")
			}
			continue
		}
		if kind := relationKind(options.flags); kind != "" {
			relation, err := parseRelation(file, field, fieldName, kind, options)
			if err != nil {
				return modelDefinition{}, err
			}
			definition.Relations = append(definition.Relations, relation)
			continue
		}
		modelField, err := parseColumn(file, field, fieldName, dbTag, options, scalars)
		if err != nil {
			return modelDefinition{}, err
		}
		if previous, exists := columns[modelField.Column]; exists {
			return modelDefinition{}, schemaError(file.name, line, "duplicate column %s used by fields %s and %s", modelField.Column, previous, fieldName)
		}
		columns[modelField.Column] = fieldName
		if modelField.Primary {
			primaryCount++
		}
		definition.Fields = append(definition.Fields, modelField)
	}
	if len(definition.Fields) == 0 {
		return modelDefinition{}, schemaError(file.name, file.fset.Position(structure.Pos()).Line, "model %s has no persistent fields", name)
	}
	if primaryCount != 1 {
		return modelDefinition{}, schemaError(file.name, file.fset.Position(structure.Pos()).Line, "model %s must declare exactly one primary field", name)
	}
	return definition, nil
}

type forgeOptions struct {
	flags  map[string]bool
	values map[string]string
}

func parseForgeOptions(value string) (forgeOptions, error) {
	result := forgeOptions{flags: make(map[string]bool), values: make(map[string]string)}
	if value == "" {
		return result, nil
	}
	parts, err := splitForgeTag(value)
	if err != nil {
		return result, err
	}
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			return result, fmt.Errorf("empty forge tag option")
		}
		key, value, hasValue := strings.Cut(part, "=")
		if !safeOptionName(key) {
			return result, fmt.Errorf("unsafe forge tag option %q", key)
		}
		if _, exists := result.flags[key]; exists {
			return result, fmt.Errorf("duplicate forge tag option %s", key)
		}
		if _, exists := result.values[key]; exists {
			return result, fmt.Errorf("duplicate forge tag option %s", key)
		}
		if hasValue {
			value = strings.TrimSpace(value)
			if value == "" {
				return result, fmt.Errorf("forge tag option %s has no value", key)
			}
			result.values[key] = value
		} else {
			result.flags[key] = true
		}
	}
	return result, nil
}

func parseColumn(file *parsedModelFile, field *ast.Field, name, dbTag string, options forgeOptions, scalars map[string]scalarType) (modelField, error) {
	line := file.fset.Position(field.Pos()).Line
	allowedFlags := map[string]bool{"primary": true, "generated": true, "protected": true, "required": true, "nullable": true, "index": true, "unique": true}
	allowedValues := map[string]bool{"type": true, "default": true, "references": true, "on_delete": true}
	if err := validateOptions(options, allowedFlags, allowedValues); err != nil {
		return modelField{}, schemaError(file.name, line, "field %s: %v", name, err)
	}
	goType, inferredDBType, family, pointerNullable, err := classifyColumnType(field.Type, file, scalars, make(map[string]bool))
	if err != nil {
		return modelField{}, schemaError(file.name, line, "field %s: %v", name, err)
	}
	generatedGoType, importPath, err := generatedColumnType(field.Type, file, scalars, make(map[string]bool))
	if err != nil {
		return modelField{}, schemaError(file.name, line, "field %s: %v", name, err)
	}
	column := dbTag
	if column == "" {
		column, err = snake(name)
		if err != nil {
			return modelField{}, schemaError(file.name, line, "field %s: derive column: %v", name, err)
		}
	}
	if column == "-" || !safeIdentifier(column) {
		return modelField{}, schemaError(file.name, line, "field %s has unsafe column name %q", name, column)
	}
	dbType := inferredDBType
	if explicit := options.values["type"]; explicit != "" {
		explicit = strings.ToLower(strings.TrimSpace(explicit))
		if !safeDatabaseType(explicit) || !compatibleDatabaseType(family, explicit) {
			return modelField{}, schemaError(file.name, line, "field %s has unsupported database type %q for %s", name, explicit, goType)
		}
		dbType = explicit
	}
	required, nullable := options.flags["required"], options.flags["nullable"]
	if required == nullable {
		return modelField{}, schemaError(file.name, line, "field %s must declare exactly one of required or nullable", name)
	}
	if pointerNullable != nullable {
		return modelField{}, schemaError(file.name, line, "field %s pointer/null wrapper and nullable metadata disagree", name)
	}
	if options.flags["primary"] && (!required || options.flags["generated"] && pointerNullable) {
		return modelField{}, schemaError(file.name, line, "primary field %s must be required and non-nullable", name)
	}
	if options.flags["generated"] && options.values["default"] != "" {
		return modelField{}, schemaError(file.name, line, "generated field %s cannot also declare a default", name)
	}
	var defaultValue *string
	if value := options.values["default"]; value != "" {
		if !safeDefault(value) || !compatibleDefault(family, dbType, nullable, value) {
			return modelField{}, schemaError(file.name, line, "field %s has unsafe or unsupported default %q", name, value)
		}
		copy := value
		defaultValue = &copy
	}
	reference, err := parseReference(options.values["references"])
	if err != nil {
		return modelField{}, schemaError(file.name, line, "field %s: %v", name, err)
	}
	onDelete := options.values["on_delete"]
	if onDelete != "" {
		if reference == nil {
			return modelField{}, schemaError(file.name, line, "field %s declares on_delete without references", name)
		}
		switch onDelete {
		case "cascade", "restrict", "set_null", "no_action":
		default:
			return modelField{}, schemaError(file.name, line, "field %s has unsupported on_delete action %q", name, onDelete)
		}
		if onDelete == "set_null" && !nullable {
			return modelField{}, schemaError(file.name, line, "field %s uses set_null but is required", name)
		}
	}
	return modelField{
		Name: name, GoType: goType, GeneratedGoType: generatedGoType, GoImportPath: importPath, Column: column, DBType: dbType,
		Primary: options.flags["primary"], Generated: options.flags["generated"], Protected: options.flags["protected"],
		Required: required, Nullable: nullable, Default: defaultValue,
		Indexed: options.flags["index"], Unique: options.flags["unique"], Reference: reference, OnDelete: onDelete,
		SourceLine: line, typeFamily: family,
	}, nil
}

func generatedColumnType(expression ast.Expr, file *parsedModelFile, scalars map[string]scalarType, visiting map[string]bool) (string, string, error) {
	prefix := ""
	if star, ok := expression.(*ast.StarExpr); ok {
		prefix = "*"
		expression = star.X
	}
	switch item := expression.(type) {
	case *ast.Ident:
		if _, exists := scalars[item.Name]; exists {
			if visiting[item.Name] {
				return "", "", fmt.Errorf("scalar type cycle involving %s", item.Name)
			}
			// Named scalar types are declared in the models package, so the
			// generated file must refer to the name rather than its underlying type.
			return prefix + item.Name, "", nil
		}
		return prefix + item.Name, "", nil
	case *ast.ArrayType:
		if item.Len == nil {
			if ident, ok := item.Elt.(*ast.Ident); ok && ident.Name == "byte" {
				return prefix + "[]byte", "", nil
			}
		}
	case *ast.SelectorExpr:
		alias, ok := item.X.(*ast.Ident)
		if !ok {
			break
		}
		importPath, exists := file.imports[alias.Name]
		if !exists {
			return "", "", fmt.Errorf("import alias %s cannot be resolved", alias.Name)
		}
		generatedAlias := map[string]string{"time": "time", "encoding/json": "json", "database/sql": "sql"}[importPath]
		if generatedAlias == "" {
			return "", "", fmt.Errorf("unsupported imported Go type %s from %s", item.Sel.Name, importPath)
		}
		return prefix + generatedAlias + "." + item.Sel.Name, importPath, nil
	}
	goType, _ := formatExpression(file.fset, expression)
	return "", "", fmt.Errorf("unsupported Go type %s", prefix+goType)
}

func parseRelation(file *parsedModelFile, field *ast.Field, name, kind string, options forgeOptions) (modelRelation, error) {
	line := file.fset.Position(field.Pos()).Line
	allowedFlags := map[string]bool{relationBelongsTo: true, relationHasOne: true, relationHasMany: true, relationManyToMany: true}
	allowedValues := map[string]bool{
		"target": true, "foreign_key": true, "references": true, "target_key": true,
		"join_table": true, "join_foreign_key": true, "join_reference_key": true,
	}
	if err := validateOptions(options, allowedFlags, allowedValues); err != nil {
		return modelRelation{}, schemaError(file.name, line, "relation %s: %v", name, err)
	}
	target := options.values["target"]
	if target == "" || !token.IsIdentifier(target) || !ast.IsExported(target) {
		return modelRelation{}, schemaError(file.name, line, "relation %s requires an exported target model", name)
	}
	declaredTarget, collection, pointer, err := relationFieldTarget(field.Type)
	if err != nil {
		return modelRelation{}, schemaError(file.name, line, "relation %s: %v", name, err)
	}
	if declaredTarget != target {
		return modelRelation{}, schemaError(file.name, line, "relation %s target %s does not match field type %s", name, target, declaredTarget)
	}
	if (kind == relationHasMany || kind == relationManyToMany) != collection {
		return modelRelation{}, schemaError(file.name, line, "relation %s has incompatible field shape for %s", name, kind)
	}
	relation := modelRelation{
		Name: name, Kind: kind, Target: target, Pointer: pointer, ForeignKey: options.values["foreign_key"],
		References: options.values["references"], TargetKey: options.values["target_key"],
		JoinTable: options.values["join_table"], JoinForeignKey: options.values["join_foreign_key"],
		JoinReferenceKey: options.values["join_reference_key"], SourceLine: line,
	}
	for _, key := range []struct{ label, value string }{
		{"foreign_key", relation.ForeignKey}, {"references", relation.References}, {"target_key", relation.TargetKey},
	} {
		if key.value != "" && (!token.IsIdentifier(key.value) || !ast.IsExported(key.value)) {
			return modelRelation{}, schemaError(file.name, line, "relation %s has unsafe %s %q", name, key.label, key.value)
		}
	}
	if kind == relationManyToMany {
		if relation.References == "" || relation.TargetKey == "" || relation.JoinTable == "" || relation.JoinForeignKey == "" || relation.JoinReferenceKey == "" || relation.ForeignKey != "" {
			return modelRelation{}, schemaError(file.name, line, "many_to_many relation %s requires references, target_key, join_table, join_foreign_key, and join_reference_key", name)
		}
		for _, key := range []struct{ label, value string }{
			{"join_table", relation.JoinTable}, {"join_foreign_key", relation.JoinForeignKey}, {"join_reference_key", relation.JoinReferenceKey},
		} {
			if !safeIdentifier(key.value) {
				return modelRelation{}, schemaError(file.name, line, "relation %s has unsafe %s %q", name, key.label, key.value)
			}
		}
	} else if relation.ForeignKey == "" || relation.References == "" || relation.TargetKey != "" || relation.JoinTable != "" || relation.JoinForeignKey != "" || relation.JoinReferenceKey != "" {
		return modelRelation{}, schemaError(file.name, line, "%s relation %s requires exactly foreign_key and references", kind, name)
	}
	return relation, nil
}

func validateModelLinks(model *modelDefinition, models map[string]*modelDefinition, filename string) error {
	fields := fieldMap(model)
	for index := range model.Fields {
		field := &model.Fields[index]
		if field.Reference == nil {
			continue
		}
		target := models[field.Reference.Model]
		if target == nil {
			return schemaError(filename, field.SourceLine, "field %s references missing model %s", field.Name, field.Reference.Model)
		}
		targetField := fieldMap(target)[field.Reference.Field]
		if targetField == nil {
			return schemaError(filename, field.SourceLine, "field %s references missing key %s.%s", field.Name, target.Name, field.Reference.Field)
		}
		if !targetField.Primary && !targetField.Unique {
			return schemaError(filename, field.SourceLine, "field %s references non-key field %s.%s", field.Name, target.Name, targetField.Name)
		}
		if !databaseTypesCompatible(field.DBType, targetField.DBType) {
			return schemaError(filename, field.SourceLine, "field %s type is incompatible with %s.%s", field.Name, target.Name, targetField.Name)
		}
		field.Reference.Table, field.Reference.Column = target.Table, targetField.Column
	}
	seenRelations := make(map[string]string)
	for index := range model.Relations {
		relation := &model.Relations[index]
		target := models[relation.Target]
		if target == nil {
			return schemaError(filename, relation.SourceLine, "relation %s targets missing model %s", relation.Name, relation.Target)
		}
		targetFields := fieldMap(target)
		var localKey, remoteKey *modelField
		switch relation.Kind {
		case relationBelongsTo:
			localKey, remoteKey = fields[relation.ForeignKey], targetFields[relation.References]
			if localKey != nil && (localKey.Reference == nil || localKey.Reference.Model != target.Name || localKey.Reference.Field != relation.References) {
				return schemaError(filename, relation.SourceLine, "belongs_to relation %s does not match %s reference metadata", relation.Name, relation.ForeignKey)
			}
		case relationHasOne, relationHasMany:
			localKey, remoteKey = fields[relation.References], targetFields[relation.ForeignKey]
			if remoteKey != nil && (remoteKey.Reference == nil || remoteKey.Reference.Model != model.Name || remoteKey.Reference.Field != relation.References) {
				return schemaError(filename, relation.SourceLine, "%s relation %s does not match %s.%s reference metadata", relation.Kind, relation.Name, target.Name, relation.ForeignKey)
			}
		case relationManyToMany:
			localKey, remoteKey = fields[relation.References], targetFields[relation.TargetKey]
		}
		if localKey == nil {
			return schemaError(filename, relation.SourceLine, "relation %s uses missing local key", relation.Name)
		}
		if remoteKey == nil {
			return schemaError(filename, relation.SourceLine, "relation %s uses missing target key", relation.Name)
		}
		if !localKey.Primary && !localKey.Unique && relation.Kind != relationBelongsTo {
			return schemaError(filename, relation.SourceLine, "relation %s local reference is not a key", relation.Name)
		}
		if relation.Kind == relationBelongsTo && !remoteKey.Primary && !remoteKey.Unique || relation.Kind == relationManyToMany && !remoteKey.Primary && !remoteKey.Unique {
			return schemaError(filename, relation.SourceLine, "relation %s target reference is not a key", relation.Name)
		}
		if !databaseTypesCompatible(localKey.DBType, remoteKey.DBType) {
			return schemaError(filename, relation.SourceLine, "relation %s key types are incompatible", relation.Name)
		}
		signature := strings.Join([]string{relation.Kind, relation.Target, relation.ForeignKey, relation.References, relation.TargetKey, relation.JoinTable, relation.JoinForeignKey, relation.JoinReferenceKey}, "|")
		if previous, exists := seenRelations[signature]; exists {
			return schemaError(filename, relation.SourceLine, "relation %s is ambiguous with %s", relation.Name, previous)
		}
		seenRelations[signature] = relation.Name
	}
	return nil
}

func rejectReferenceCycles(models []parsedModel) error {
	edges := make(map[string][]string)
	files := make(map[string]string)
	for _, model := range models {
		files[model.definition.Name] = model.file.name
		seen := make(map[string]bool)
		for _, field := range model.definition.Fields {
			if field.Reference != nil && field.Reference.Model != model.definition.Name && !seen[field.Reference.Model] {
				edges[model.definition.Name] = append(edges[model.definition.Name], field.Reference.Model)
				seen[field.Reference.Model] = true
			}
		}
		sort.Strings(edges[model.definition.Name])
	}
	state := make(map[string]uint8)
	var stack []string
	var visit func(string) error
	visit = func(name string) error {
		state[name] = 1
		stack = append(stack, name)
		for _, target := range edges[name] {
			if state[target] == 0 {
				if err := visit(target); err != nil {
					return err
				}
			} else if state[target] == 1 {
				start := 0
				for stack[start] != target {
					start++
				}
				cycle := append(append([]string(nil), stack[start:]...), target)
				return schemaError(files[name], 0, "foreign-key cycle cannot be emitted as ordered create-table migrations: %s", strings.Join(cycle, " -> "))
			}
		}
		stack = stack[:len(stack)-1]
		state[name] = 2
		return nil
	}
	for _, model := range models {
		if state[model.definition.Name] == 0 {
			if err := visit(model.definition.Name); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateGeneratedDatabaseNames(models []parsedModel) error {
	seen := make(map[string]string)
	claim := func(name, owner, filename string, line int) error {
		if !safeIdentifier(name) {
			return schemaError(filename, line, "generated database identifier %q for %s exceeds PostgreSQL's 63-byte limit", name, owner)
		}
		if previous, exists := seen[name]; exists && previous != owner {
			return schemaError(filename, line, "generated database identifier %q for %s conflicts with %s", name, owner, previous)
		}
		seen[name] = owner
		return nil
	}
	for _, parsed := range models {
		model := parsed.definition
		if err := claim(model.Table+"_pkey", model.Name+" primary key", parsed.file.name, 0); err != nil {
			return err
		}
		for _, field := range model.Fields {
			owner := model.Name + "." + field.Name
			if field.Indexed {
				if err := claim(model.Table+"_"+field.Column+"_idx", owner+" index", parsed.file.name, field.SourceLine); err != nil {
					return err
				}
			}
			if field.Unique {
				if err := claim(model.Table+"_"+field.Column+"_key", owner+" unique constraint", parsed.file.name, field.SourceLine); err != nil {
					return err
				}
			}
			if field.Reference != nil {
				if err := claim(model.Table+"_"+field.Column+"_fkey", owner+" foreign key", parsed.file.name, field.SourceLine); err != nil {
					return err
				}
			}
		}
		for _, relation := range model.Relations {
			if relation.Kind != relationManyToMany {
				continue
			}
			for _, generated := range []struct{ name, purpose string }{
				{relation.JoinTable + "_" + relation.JoinForeignKey + "_idx", "join foreign index"},
				{relation.JoinTable + "_" + relation.JoinReferenceKey + "_idx", "join reference index"},
				{relation.JoinTable + "_" + relation.JoinForeignKey + "_fkey", "join foreign constraint"},
				{relation.JoinTable + "_" + relation.JoinReferenceKey + "_fkey", "join reference constraint"},
				{relation.JoinTable + "_" + relation.JoinForeignKey + "_" + relation.JoinReferenceKey + "_key", "join unique constraint"},
			} {
				if err := claim(generated.name, model.Name+"."+relation.Name+" "+generated.purpose, parsed.file.name, relation.SourceLine); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func classifyColumnType(expression ast.Expr, file *parsedModelFile, scalars map[string]scalarType, visiting map[string]bool) (string, string, string, bool, error) {
	goType, err := formatExpression(file.fset, expression)
	if err != nil {
		return "", "", "", false, err
	}
	pointer := false
	if star, ok := expression.(*ast.StarExpr); ok {
		pointer = true
		expression = star.X
	}
	switch item := expression.(type) {
	case *ast.Ident:
		if scalar, exists := scalars[item.Name]; exists {
			if visiting[item.Name] {
				return "", "", "", false, fmt.Errorf("scalar type cycle involving %s", item.Name)
			}
			visiting[item.Name] = true
			_, dbType, family, nullable, err := classifyColumnType(scalar.expression, scalar.file, scalars, visiting)
			delete(visiting, item.Name)
			return goType, dbType, family, pointer || nullable, err
		}
		dbType, family, ok := builtinColumnType(item.Name)
		if !ok {
			return "", "", "", false, fmt.Errorf("unsupported Go type %s", goType)
		}
		return goType, dbType, family, pointer, nil
	case *ast.ArrayType:
		if item.Len == nil {
			if ident, ok := item.Elt.(*ast.Ident); ok && ident.Name == "byte" {
				return goType, "bytea", "bytes", pointer, nil
			}
		}
		return "", "", "", false, fmt.Errorf("unsupported Go type %s", goType)
	case *ast.SelectorExpr:
		alias, ok := item.X.(*ast.Ident)
		if !ok {
			return "", "", "", false, fmt.Errorf("unsupported qualified Go type %s", goType)
		}
		importPath, exists := file.imports[alias.Name]
		if !exists {
			return "", "", "", false, fmt.Errorf("import alias %s cannot be resolved", alias.Name)
		}
		dbType, family, nullable, ok := importedColumnType(importPath, item.Sel.Name)
		if !ok {
			return "", "", "", false, fmt.Errorf("unsupported imported Go type %s from %s", item.Sel.Name, importPath)
		}
		return goType, dbType, family, pointer || nullable, nil
	default:
		return "", "", "", false, fmt.Errorf("unsupported Go type %s", goType)
	}
}

func builtinColumnType(name string) (string, string, bool) {
	switch name {
	case "string":
		return "text", "string", true
	case "bool":
		return "boolean", "bool", true
	case "int8", "int16":
		return "smallint", "integer", true
	case "int", "int32", "uint8", "uint16":
		return "integer", "integer", true
	case "int64", "uint", "uint32", "uint64":
		return "bigint", "integer", true
	case "float32":
		return "real", "float", true
	case "float64":
		return "double precision", "float", true
	default:
		return "", "", false
	}
}

func importedColumnType(importPath, name string) (string, string, bool, bool) {
	switch importPath + "." + name {
	case "time.Time":
		return "timestamptz", "time", false, true
	case "encoding/json.RawMessage":
		return "jsonb", "json", false, true
	case "database/sql.NullString":
		return "text", "string", true, true
	case "database/sql.NullBool":
		return "boolean", "bool", true, true
	case "database/sql.NullInt16":
		return "smallint", "integer", true, true
	case "database/sql.NullInt32":
		return "integer", "integer", true, true
	case "database/sql.NullInt64":
		return "bigint", "integer", true, true
	case "database/sql.NullFloat64":
		return "double precision", "float", true, true
	case "database/sql.NullTime":
		return "timestamptz", "time", true, true
	default:
		return "", "", false, false
	}
}

func safeDatabaseType(value string) bool {
	switch value {
	case "smallint", "integer", "bigint", "real", "double precision", "numeric", "boolean", "text", "bytea", "date", "timestamp", "timestamptz", "uuid", "json", "jsonb":
		return true
	default:
		return sizedDatabaseType.MatchString(value) || numericDatabaseType.MatchString(value)
	}
}

func compatibleDatabaseType(family, value string) bool {
	base := value
	if index := strings.IndexByte(base, '('); index >= 0 {
		base = base[:index]
	}
	switch family {
	case "string":
		return base == "text" || base == "varchar" || base == "character varying" || base == "uuid"
	case "integer":
		return base == "smallint" || base == "integer" || base == "bigint" || base == "numeric"
	case "float":
		return base == "real" || base == "double precision" || base == "numeric"
	case "bool":
		return base == "boolean"
	case "bytes":
		return base == "bytea"
	case "time":
		return base == "date" || base == "timestamp" || base == "timestamptz"
	case "json":
		return base == "json" || base == "jsonb" || base == "bytea"
	default:
		return false
	}
}

func databaseTypesCompatible(left, right string) bool {
	normalize := func(value string) string {
		value = strings.ToLower(strings.TrimSpace(value))
		if strings.HasPrefix(value, "varchar(") || strings.HasPrefix(value, "character varying(") || value == "text" {
			return "text"
		}
		return value
	}
	return normalize(left) == normalize(right)
}

func safeDefault(value string) bool {
	if strings.TrimSpace(value) != value || strings.ContainsAny(value, ";\r\n\x00") || strings.Contains(value, "--") || strings.Contains(value, "/*") || strings.Contains(value, "*/") {
		return false
	}
	switch strings.ToLower(value) {
	case "true", "false", "null", "now()", "current_timestamp", "gen_random_uuid()":
		return true
	default:
		return integerDefault.MatchString(value) || decimalDefault.MatchString(value) || quotedDefault.MatchString(value)
	}
}

func compatibleDefault(family, dbType string, nullable bool, value string) bool {
	lower := strings.ToLower(value)
	if lower == "null" {
		return nullable
	}
	if lower == "now()" || lower == "current_timestamp" {
		return family == "time"
	}
	if lower == "gen_random_uuid()" {
		return family == "string" && dbType == "uuid"
	}
	if lower == "true" || lower == "false" {
		return family == "bool"
	}
	if quotedDefault.MatchString(value) {
		return family == "string" || family == "time"
	}
	if decimalDefault.MatchString(value) {
		return family == "integer" || family == "float"
	}
	return false
}

func parseReference(value string) (*modelReference, error) {
	if value == "" {
		return nil, nil
	}
	model, field, ok := strings.Cut(value, ".")
	if !ok || strings.Contains(field, ".") || !token.IsIdentifier(model) || !ast.IsExported(model) || !token.IsIdentifier(field) || !ast.IsExported(field) {
		return nil, fmt.Errorf("references must use Model.Field, got %q", value)
	}
	return &modelReference{Model: model, Field: field}, nil
}

func relationFieldTarget(expression ast.Expr) (string, bool, bool, error) {
	pointer := false
	if star, ok := expression.(*ast.StarExpr); ok {
		pointer = true
		expression = star.X
	}
	collection := false
	if slice, ok := expression.(*ast.ArrayType); ok && slice.Len == nil {
		collection = true
		expression = slice.Elt
		if star, ok := expression.(*ast.StarExpr); ok {
			pointer = true
			expression = star.X
		}
	}
	ident, ok := expression.(*ast.Ident)
	if !ok || !ast.IsExported(ident.Name) {
		return "", false, false, fmt.Errorf("field type must be a local exported model or slice of models")
	}
	return ident.Name, collection, pointer, nil
}

func relationKind(flags map[string]bool) string {
	var found string
	for _, kind := range []string{relationBelongsTo, relationHasOne, relationHasMany, relationManyToMany} {
		if flags[kind] {
			if found != "" {
				return "multiple"
			}
			found = kind
		}
	}
	return found
}

func validateOptions(options forgeOptions, flags, values map[string]bool) error {
	flagNames := make([]string, 0, len(options.flags))
	for key := range options.flags {
		flagNames = append(flagNames, key)
	}
	sort.Strings(flagNames)
	for _, key := range flagNames {
		if !flags[key] {
			return fmt.Errorf("unsupported forge flag %s", key)
		}
	}
	valueNames := make([]string, 0, len(options.values))
	for key := range options.values {
		valueNames = append(valueNames, key)
	}
	sort.Strings(valueNames)
	for _, key := range valueNames {
		if !values[key] {
			return fmt.Errorf("unsupported forge option %s", key)
		}
	}
	if relationKind(options.flags) == "multiple" {
		return fmt.Errorf("a field cannot declare multiple relation kinds")
	}
	return nil
}

func fieldMap(model *modelDefinition) map[string]*modelField {
	result := make(map[string]*modelField, len(model.Fields))
	for index := range model.Fields {
		result[model.Fields[index].Name] = &model.Fields[index]
	}
	return result
}

func modelFieldTags(field *ast.Field) (string, string, error) {
	if field.Tag == nil {
		return "", "", nil
	}
	forge, err := sourceStructTag(field.Tag.Value, "forge")
	if err != nil {
		return "", "", err
	}
	db, err := sourceStructTag(field.Tag.Value, "db")
	if err != nil {
		return "", "", err
	}
	return forge, db, nil
}

func sourceStructTag(literal, wanted string) (string, error) {
	raw, err := strconv.Unquote(literal)
	if err != nil {
		return "", fmt.Errorf("invalid struct tag: %w", err)
	}
	var found string
	foundWanted := false
	for raw != "" {
		raw = strings.TrimLeftFunc(raw, unicode.IsSpace)
		if raw == "" {
			break
		}
		colon := strings.IndexByte(raw, ':')
		if colon <= 0 || colon+1 >= len(raw) || raw[colon+1] != '"' {
			return "", fmt.Errorf("malformed struct tag")
		}
		key := raw[:colon]
		end := colon + 2
		for end < len(raw) {
			if raw[end] == '\\' {
				end += 2
				continue
			}
			if raw[end] == '"' {
				break
			}
			end++
		}
		if end >= len(raw) {
			return "", fmt.Errorf("unterminated struct tag value")
		}
		value, err := strconv.Unquote(raw[colon+1 : end+1])
		if err != nil {
			return "", fmt.Errorf("invalid struct tag value: %w", err)
		}
		if key == wanted {
			if foundWanted {
				return "", fmt.Errorf("duplicate %s struct tag", wanted)
			}
			found, foundWanted = value, true
		}
		raw = raw[end+1:]
	}
	return found, nil
}

func splitForgeTag(value string) ([]string, error) {
	var parts []string
	start, depth := 0, 0
	var quote rune
	escaped := false
	for index, character := range value {
		if escaped {
			escaped = false
			continue
		}
		if character == '\\' && quote != 0 {
			escaped = true
			continue
		}
		if quote != 0 {
			if character == quote {
				quote = 0
			}
			continue
		}
		switch character {
		case '\'', '"':
			quote = character
		case '(':
			depth++
		case ')':
			depth--
			if depth < 0 {
				return nil, fmt.Errorf("unbalanced forge tag parentheses")
			}
		case ',':
			if depth == 0 {
				parts = append(parts, value[start:index])
				start = index + 1
			}
		}
	}
	if quote != 0 || depth != 0 {
		return nil, fmt.Errorf("unterminated forge tag value")
	}
	return append(parts, value[start:]), nil
}

func formatExpression(fset *token.FileSet, expression ast.Expr) (string, error) {
	var output bytes.Buffer
	if err := format.Node(&output, fset, expression); err != nil {
		return "", fmt.Errorf("format Go type: %w", err)
	}
	return output.String(), nil
}

func safeIdentifier(value string) bool {
	return len(value) <= 63 && databaseIdentifier.MatchString(value)
}

func hasBuildConstraint(file *ast.File) bool {
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			continue
		}
		for _, comment := range group.List {
			text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
			if strings.HasPrefix(text, "go:build") || strings.HasPrefix(text, "+build") {
				return true
			}
		}
	}
	return false
}

func constrainedModelFilename(name string) bool {
	stem := strings.TrimSuffix(name, ".go")
	parts := strings.Split(stem, "_")
	if len(parts) < 2 {
		return false
	}
	last := parts[len(parts)-1]
	if knownGOOS[last] || knownGOARCH[last] {
		return true
	}
	if len(parts) >= 3 {
		return knownGOOS[parts[len(parts)-2]] && knownGOARCH[last]
	}
	return false
}

var knownGOOS = map[string]bool{
	"aix": true, "android": true, "darwin": true, "dragonfly": true,
	"freebsd": true, "illumos": true, "ios": true, "js": true,
	"linux": true, "netbsd": true, "openbsd": true, "plan9": true,
	"solaris": true, "wasip1": true, "windows": true,
}

var knownGOARCH = map[string]bool{
	"386": true, "amd64": true, "amd64p32": true, "arm": true,
	"arm64": true, "loong64": true, "mips": true, "mips64": true,
	"mips64le": true, "mipsle": true, "ppc64": true, "ppc64le": true,
	"riscv64": true, "s390x": true, "sparc64": true, "wasm": true,
}

func safeOptionName(value string) bool {
	if value == "" {
		return false
	}
	for _, character := range value {
		if character != '_' && (character < 'a' || character > 'z') {
			return false
		}
	}
	return true
}

func schemaError(filename string, line int, format string, arguments ...any) error {
	message := fmt.Sprintf(format, arguments...)
	if line > 0 {
		return fmt.Errorf("%s:%d: %s", filepath.ToSlash(filename), line, message)
	}
	return fmt.Errorf("%s: %s", filepath.ToSlash(filename), message)
}
