package cli

import (
	"bytes"
	"errors"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestORMGenerateProducesDeterministicInspectableCode(t *testing.T) {
	directory := writeORMProject(t, validORMModels)
	t.Chdir(directory)
	var output bytes.Buffer
	if err := Run([]string{"orm:generate"}, &output, &output); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(output.String(), "created "+generatedORMPath) {
		t.Fatalf("generation output = %q", output.String())
	}
	artifact := readORMArtifact(t)
	for _, expected := range []string{
		"// Code generated by GoForge. DO NOT EDIT.",
		"var IssueMapper = orm.MustMapper[Issue]",
		"var IssueTable = orm.MustTable(\"issues\", IssueMapper)",
		"orm.Column[Issue, int64]",
		"type IssueCreateInput struct",
		"Name      string",
		"Note      orm.Field[*string]",
		"Published orm.Field[bool]",
		"type IssueChanges struct",
		"func (store Store) Issues() IssueQuery",
		"additional ...orm.Assignment[Issue]",
		"func IssueOwnerRelation(options orm.RelationOptions) orm.BelongsTo[Issue, User, int64]",
		"var IssueRelations = struct",
		"func (query IssueQuery) LoadOwner(ctx context.Context",
	} {
		if !strings.Contains(artifact, expected) {
			t.Errorf("generated ORM is missing %q:\n%s", expected, artifact)
		}
	}
	for _, forbidden := range []string{"model.Owner", "belongs_to", "reflect"} {
		if strings.Contains(artifact, forbidden) {
			t.Errorf("generated ORM unexpectedly contains %q", forbidden)
		}
	}
	createStart := strings.Index(artifact, "type IssueCreateInput struct")
	createEnd := strings.Index(artifact[createStart:], "}\n") + createStart
	create := artifact[createStart:createEnd]
	for _, protected := range []string{"ID ", "UserID ", "CreatedAt "} {
		if strings.Contains(create, protected) {
			t.Errorf("create input exposes protected/generated field %q:\n%s", protected, create)
		}
	}
	if _, err := parser.ParseFile(token.NewFileSet(), generatedORMPath, artifact, parser.AllErrors); err != nil {
		t.Fatalf("generated artifact is not Go: %v", err)
	}

	first := append([]byte(nil), []byte(artifact)...)
	writes := 0
	if err := generateORMWith(false, &output, renderORMArtifact, func(string, []byte) error {
		writes++
		return errors.New("identical output should not be written")
	}); err != nil {
		t.Fatal(err)
	}
	if writes != 0 || !bytes.Equal(first, []byte(readORMArtifact(t))) {
		t.Fatalf("identical generation wrote %d times or changed output", writes)
	}

	var check bytes.Buffer
	if err := Run([]string{"orm:generate", "--check"}, &check, &check); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(check.String(), generatedORMPath+" is current") {
		t.Fatalf("check output = %q", check.String())
	}
}

func TestORMGenerateCompilesRelationshipRichModelsAndBudgetsQueries(t *testing.T) {
	root := projectRoot(t)
	directory := writeORMProject(t, relationshipRichORMModels)
	t.Chdir(directory)
	var output bytes.Buffer
	if err := generateORM(false, &output); err != nil {
		t.Fatal(err)
	}
	artifact := readORMArtifact(t)
	for _, expected := range []string{
		"orm.BelongsTo[Post, User, int64]",
		"orm.HasOne[User, Profile, int64]",
		"orm.HasMany[User, Post, int64]",
		"orm.ManyToMany[Post, Tag, int64, int64]",
		"if parent.AuthorID == nil",
		"if target.UserID == nil",
		"func (query PostQuery) AttachTags",
		"func (query PostQuery) DetachTags",
	} {
		if !strings.Contains(artifact, expected) {
			t.Errorf("generated relationships are missing %q:\n%s", expected, artifact)
		}
	}

	module := "module example.com/generated-relations\n\ngo 1.25\n\nrequire github.com/ShanilKoshitha/goforge v0.0.0\n\nreplace github.com/ShanilKoshitha/goforge => " + filepath.ToSlash(root) + "\n"
	if err := os.WriteFile("go.mod", []byte(module), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join("internal", "models", "zz_orm_relations_gen_test.go"), []byte(generatedORMRelationshipTest), 0o644); err != nil {
		t.Fatal(err)
	}
	command := exec.Command("go", "test", "-mod=mod", "./internal/models")
	command.Dir = directory
	command.Env = append(os.Environ(),
		"GOCACHE="+filepath.Join(root, ".cache", "go-build"),
		"GOMODCACHE="+filepath.Join(root, ".cache", "go-mod"),
		"GOWORK=off",
	)
	if result, err := command.CombinedOutput(); err != nil {
		t.Fatalf("generated relationships do not compile and execute: %v\n%s\n%s", err, result, artifact)
	}
}

func TestORMGenerateCheckDetectsMissingAndStaleWithoutWriting(t *testing.T) {
	directory := writeORMProject(t, validORMModels)
	t.Chdir(directory)
	var output bytes.Buffer
	if err := Run([]string{"orm:generate", "--check"}, &output, &output); err == nil || !strings.Contains(err.Error(), "generated ORM is missing") {
		t.Fatalf("missing check error = %v", err)
	}
	if _, err := os.Stat(filepath.FromSlash(generatedORMPath)); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("check mode created output: %v", err)
	}
	if err := Run([]string{"orm:generate"}, &output, &output); err != nil {
		t.Fatal(err)
	}
	before := readORMArtifact(t)
	modelPath := filepath.Join("internal", "models", "z_issue.go")
	changed := strings.Replace(validORMModels["z_issue.go"], "\tOwner     User", "\tPriority  int64 `forge:\"required,default=0\"`\n\tOwner     User", 1)
	if err := os.WriteFile(modelPath, []byte(changed), 0o644); err != nil {
		t.Fatal(err)
	}
	writes := 0
	err := generateORMWith(true, &output, renderORMArtifact, func(string, []byte) error {
		writes++
		return nil
	})
	if err == nil || !strings.Contains(err.Error(), "generated ORM is stale") {
		t.Fatalf("stale check error = %v", err)
	}
	if writes != 0 || readORMArtifact(t) != before {
		t.Fatal("stale check wrote or changed the last generated artifact")
	}
}

func TestORMGenerateRetainsLastGoodArtifactOnFailures(t *testing.T) {
	directory := writeORMProject(t, validORMModels)
	t.Chdir(directory)
	var output bytes.Buffer
	if err := generateORM(false, &output); err != nil {
		t.Fatal(err)
	}
	before := readORMArtifact(t)
	modelPath := filepath.Join("internal", "models", "z_issue.go")
	if err := os.WriteFile(modelPath, []byte("package models\ntype Broken struct {\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := generateORM(false, &output); err == nil || !strings.Contains(err.Error(), "parse ORM models") {
		t.Fatalf("parse error = %v", err)
	}
	if readORMArtifact(t) != before {
		t.Fatal("parse failure changed last good artifact")
	}
	if err := os.WriteFile(modelPath, []byte(validORMModels["z_issue.go"]), 0o644); err != nil {
		t.Fatal(err)
	}

	for _, failure := range []struct {
		name   string
		render ormArtifactRenderer
		write  ormArtifactWriter
	}{
		{
			name: "render or format",
			render: func(modelSchema) (string, error) {
				return "", errors.New("injected format failure")
			},
			write: func(string, []byte) error { t.Fatal("writer called after render failure"); return nil },
		},
		{
			name:   "publication",
			render: func(modelSchema) (string, error) { return before + "// stale\n", nil },
			write:  func(string, []byte) error { return errors.New("injected write failure") },
		},
	} {
		t.Run(failure.name, func(t *testing.T) {
			if err := generateORMWith(false, &output, failure.render, failure.write); err == nil {
				t.Fatal("expected injected failure")
			}
			if readORMArtifact(t) != before {
				t.Fatal("failure changed last good artifact")
			}
		})
	}
}

func TestORMGenerateReplacesCorruptSelfIdentifiedArtifact(t *testing.T) {
	directory := writeORMProject(t, validORMModels)
	t.Chdir(directory)
	path := filepath.FromSlash(generatedORMPath)
	corrupt := "// Code generated by GoForge. DO NOT EDIT.\npackage models\nthis is not Go\n"
	if err := os.WriteFile(path, []byte(corrupt), 0o644); err != nil {
		t.Fatal(err)
	}
	var output bytes.Buffer
	if err := generateORM(false, &output); err != nil {
		t.Fatal(err)
	}
	artifact := readORMArtifact(t)
	if artifact == corrupt || !strings.Contains(artifact, "var IssueMapper") {
		t.Fatal("generator did not replace its corrupt self-identified artifact")
	}
}

func TestORMGenerateRejectsDeclarationCollisionsBeforeWriting(t *testing.T) {
	tests := []struct {
		name   string
		source string
		want   string
	}{
		{
			name: "store",
			source: `package models
type Store struct { ID int64 ` + "`forge:\"primary,required\"`" + ` }
`,
			want: "generated declaration Store",
		},
		{
			name: "derived declaration",
			source: `package models
type User struct { ID int64 ` + "`forge:\"primary,required\"`" + ` }
type UserMapper = string
`,
			want: "generated declaration UserMapper",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			directory := writeORMProject(t, map[string]string{"model.go": test.source})
			t.Chdir(directory)
			var output bytes.Buffer
			err := generateORM(false, &output)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("collision error = %v", err)
			}
			if _, err := os.Stat(filepath.FromSlash(generatedORMPath)); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("collision generated output: %v", err)
			}
		})
	}
}

func TestORMGenerateCompilesAndExecutesWithDBAndTx(t *testing.T) {
	root := projectRoot(t)
	directory := writeORMProject(t, validORMModels)
	t.Chdir(directory)
	var output bytes.Buffer
	if err := generateORM(false, &output); err != nil {
		t.Fatal(err)
	}
	module := "module example.com/generated\n\ngo 1.25\n\nrequire github.com/ShanilKoshitha/goforge v0.0.0\n\nreplace github.com/ShanilKoshitha/goforge => " + filepath.ToSlash(root) + "\n"
	if err := os.WriteFile("go.mod", []byte(module), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join("internal", "models", "zz_orm_gen_test.go"), []byte(generatedORMExecutionTest), 0o644); err != nil {
		t.Fatal(err)
	}
	command := exec.Command("go", "test", "-mod=mod", "./internal/models")
	command.Dir = directory
	command.Env = append(os.Environ(),
		"GOCACHE="+filepath.Join(root, ".cache", "go-build"),
		"GOMODCACHE="+filepath.Join(root, ".cache", "go-mod"),
		"GOWORK=off",
	)
	if result, err := command.CombinedOutput(); err != nil {
		t.Fatalf("generated models do not compile and execute: %v\n%s\n%s", err, result, readORMArtifact(t))
	}
}

func TestORMGenerateCLIUsage(t *testing.T) {
	var output bytes.Buffer
	printHelp(&output)
	if !strings.Contains(output.String(), "forge orm:generate [--check]") {
		t.Fatalf("help omits ORM generator:\n%s", output.String())
	}
	directory := writeORMProject(t, validORMModels)
	t.Chdir(directory)
	if err := Run([]string{"orm:generate", "--write"}, &output, &output); err == nil || err.Error() != "usage: forge orm:generate [--check]" {
		t.Fatalf("invalid arguments error = %v", err)
	}
}

func TestORMGenerateRequiresSupportedProjectFormatBeforeWriting(t *testing.T) {
	for _, test := range []struct {
		version string
		want    string
	}{
		{version: "3", want: "upgrade the project to format 4"},
		{version: "10", want: "newer than this CLI supports"},
	} {
		t.Run(test.version, func(t *testing.T) {
			directory := t.TempDir()
			t.Chdir(directory)
			if err := os.WriteFile("forge.yaml", []byte("version: "+test.version+"\n"), 0o644); err != nil {
				t.Fatal(err)
			}
			var output bytes.Buffer
			err := Run([]string{"orm:generate"}, &output, &output)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("format %s error = %v", test.version, err)
			}
			if _, err := os.Stat(filepath.FromSlash(generatedORMPath)); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("format refusal wrote generated ORM: %v", err)
			}
		})
	}
}

func writeORMProject(t *testing.T, sources map[string]string) string {
	t.Helper()
	directory := t.TempDir()
	if err := os.WriteFile(filepath.Join(directory, "forge.yaml"), []byte("version: 4\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	models := filepath.Join(directory, "internal", "models")
	if err := os.MkdirAll(models, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, source := range sources {
		if err := os.WriteFile(filepath.Join(models, name), []byte(source), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return directory
}

func readORMArtifact(t *testing.T) string {
	t.Helper()
	contents, err := os.ReadFile(filepath.FromSlash(generatedORMPath))
	if err != nil {
		t.Fatal(err)
	}
	return string(contents)
}

var validORMModels = map[string]string{
	"z_issue.go": `package models

import "time"

type Issue struct {
	ID        int64     ` + "`forge:\"primary,generated,protected,required\"`" + `
	UserID    int64     ` + "`forge:\"protected,required,index,references=User.ID,on_delete=cascade\"`" + `
	Name      string    ` + "`forge:\"required\"`" + `
	Note      *string   ` + "`forge:\"nullable\"`" + `
	Published bool      ` + "`forge:\"required,default=false\"`" + `
	CreatedAt time.Time ` + "`forge:\"generated,protected,required\"`" + `
	Owner     User      ` + "`forge:\"belongs_to,target=User,foreign_key=UserID,references=ID\"`" + `
}
`,
	"a_user.go": `package models

type User struct {
	ID   int64  ` + "`forge:\"primary,generated,protected,required\"`" + `
	Name string ` + "`forge:\"required\"`" + `
}
`,
}

var relationshipRichORMModels = map[string]string{
	"a_user.go": `package models

type User struct {
	ID      int64    ` + "`forge:\"primary,generated,protected,required\"`" + `
	Name    string   ` + "`forge:\"required\"`" + `
	Profile *Profile ` + "`forge:\"has_one,target=Profile,foreign_key=UserID,references=ID\"`" + `
	Posts   []*Post  ` + "`forge:\"has_many,target=Post,foreign_key=AuthorID,references=ID\"`" + `
}
`,
	"b_profile.go": `package models

type Profile struct {
	ID     int64  ` + "`forge:\"primary,generated,protected,required\"`" + `
	UserID *int64 ` + "`forge:\"nullable,unique,references=User.ID,on_delete=set_null\"`" + `
	Bio    string ` + "`forge:\"required\"`" + `
	User   *User  ` + "`forge:\"belongs_to,target=User,foreign_key=UserID,references=ID\"`" + `
}
`,
	"c_post.go": `package models

type Post struct {
	ID       int64  ` + "`forge:\"primary,generated,protected,required\"`" + `
	AuthorID *int64 ` + "`forge:\"nullable,index,references=User.ID,on_delete=set_null\"`" + `
	Title    string ` + "`forge:\"required\"`" + `
	Author   *User  ` + "`forge:\"belongs_to,target=User,foreign_key=AuthorID,references=ID\"`" + `
	Tags     []*Tag ` + "`forge:\"many_to_many,target=Tag,references=ID,target_key=ID,join_table=post_tags,join_foreign_key=post_id,join_reference_key=tag_id\"`" + `
}
`,
	"d_tag.go": `package models

type Tag struct {
	ID   int64  ` + "`forge:\"primary,generated,protected,required\"`" + `
	Name string ` + "`forge:\"required,unique\"`" + `
}
`,
}

const generatedORMRelationshipTest = `package models

import (
	"reflect"
	"strings"
	"testing"

	forgeorm "github.com/ShanilKoshitha/goforge/orm"
)

func TestGeneratedRelationshipDescriptorsAndBudgets(t *testing.T) {
	one, two, three := int64(1), int64(2), int64(3)
	posts := []Post{{ID: 1, AuthorID: &one}, {ID: 2, AuthorID: nil}, {ID: 3, AuthorID: &two}, {ID: 4, AuthorID: &one}}
	belongsStatements, err := PostAuthorRelation(forgeorm.RelationOptions{ParameterLimit: 2}).Build(posts, forgeorm.Select(UserTable))
	if err != nil { t.Fatal(err) }
	if len(belongsStatements) != 1 || !reflect.DeepEqual(belongsStatements[0].Args(), []any{int64(1), int64(2)}) {
		t.Fatalf("nullable belongs-to keys were not normalized/deduplicated: %#v", belongsStatements)
	}

	users := []User{{ID: one}, {ID: two}, {ID: three}}
	postsScope := forgeorm.Select(PostTable).Where(PostColumns.Title.Eq("visible"))
	hasManyStatements, err := UserPostsRelation(forgeorm.RelationOptions{ParameterLimit: 2}).Build(users, postsScope)
	if err != nil { t.Fatal(err) }
	if len(hasManyStatements) != 3 {
		t.Fatalf("has-many statements = %d, want three one-key batches", len(hasManyStatements))
	}
	for index, statement := range hasManyStatements {
		want := []any{"visible", int64(index + 1)}
		if !reflect.DeepEqual(statement.Args(), want) || !strings.Contains(statement.SQL(), ` + "`\"posts\".\"title\" = $1`" + `) {
			t.Fatalf("scoped has-many statement %d: %s %#v", index, statement.SQL(), statement.Args())
		}
	}

	hasOneStatements, err := UserProfileRelation(forgeorm.RelationOptions{ParameterLimit: 2}).Build(users, forgeorm.Select(ProfileTable))
	if err != nil || len(hasOneStatements) != 2 {
		t.Fatalf("nullable has-one target key did not batch: %d %v", len(hasOneStatements), err)
	}

	tagsScope := forgeorm.Select(TagTable).Where(TagColumns.Name.Eq("go"))
	manyStatements, err := PostTagsRelation(forgeorm.RelationOptions{ParameterLimit: 2}).Build(posts[:3], tagsScope)
	if err != nil || len(manyStatements) != 3 {
		t.Fatalf("many-to-many scoped statements = %d, error %v", len(manyStatements), err)
	}
	attach, err := PostRelations.Tags.BuildAttach(7, 9)
	if err != nil || !strings.Contains(attach.SQL(), ` + "`ON CONFLICT (\"post_id\", \"tag_id\") DO NOTHING`" + `) {
		t.Fatalf("attach statement: %s %v", attach.SQL(), err)
	}
	detach, err := PostRelations.Tags.BuildDetach(7, 9)
	if err != nil || !strings.Contains(detach.SQL(), ` + "`WHERE \"post_id\" = $1 AND \"tag_id\" = $2`" + `) {
		t.Fatalf("detach statement: %s %v", detach.SQL(), err)
	}
}
`

const generatedORMExecutionTest = `package models

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"io"
	"reflect"
	"sync"
	"testing"
	"time"

	forgeorm "github.com/ShanilKoshitha/goforge/orm"
)

var registerModelDriver sync.Once

func TestGeneratedStoreExecutesThroughDBAndTx(t *testing.T) {
	registerModelDriver.Do(func() { sql.Register("goforge-generated-model-test", modelDriver{}) })
	db, err := sql.Open("goforge-generated-model-test", "")
	if err != nil { t.Fatal(err) }
	defer db.Close()
	store := NewStore(db)
	issues := store.Issues()
	nullInsert, err := issues.Create(IssueCreateInput{Name: "created", Note: forgeorm.Null[*string]()}, IssueColumns.UserID.Set(7)).Build()
	if err != nil { t.Fatal(err) }
	if nullInsert.SQL() != ` + "`INSERT INTO \"issues\" (\"name\", \"note\", \"user_id\") VALUES ($1, $2, $3) RETURNING \"issues\".\"id\", \"issues\".\"user_id\", \"issues\".\"name\", \"issues\".\"note\", \"issues\".\"published\", \"issues\".\"created_at\"`" + ` || !reflect.DeepEqual(nullInsert.Args(), []any{"created", nil, int64(7)}) { t.Fatalf("null/default insert: %s %#v", nullInsert.SQL(), nullInsert.Args()) }
	valueInsert, err := issues.Create(IssueCreateInput{Name: "created", Published: forgeorm.Value(true)}, IssueColumns.UserID.Set(7)).Build()
	if err != nil { t.Fatal(err) }
	if valueInsert.SQL() != ` + "`INSERT INTO \"issues\" (\"name\", \"published\", \"user_id\") VALUES ($1, $2, $3) RETURNING \"issues\".\"id\", \"issues\".\"user_id\", \"issues\".\"name\", \"issues\".\"note\", \"issues\".\"published\", \"issues\".\"created_at\"`" + ` || !reflect.DeepEqual(valueInsert.Args(), []any{"created", true, int64(7)}) { t.Fatalf("value/default insert: %s %#v", valueInsert.SQL(), valueInsert.Args()) }
	update, err := issues.Update(IssueChanges{Name: forgeorm.Value("changed"), Note: forgeorm.Null[*string]()} ).Where(IssueColumns.ID.Eq(11), IssueColumns.UserID.Eq(7)).Build()
	if err != nil { t.Fatal(err) }
	if update.SQL() != ` + "`UPDATE \"issues\" SET \"name\" = $1, \"note\" = $2 WHERE \"issues\".\"id\" = $3 AND \"issues\".\"user_id\" = $4`" + ` || !reflect.DeepEqual(update.Args(), []any{"changed", nil, int64(11), int64(7)}) { t.Fatalf("partial update: %s %#v", update.SQL(), update.Args()) }
	fromDB, err := issues.Select().First(context.Background(), issues.Executor)
	if err != nil || fromDB.ID != 11 || fromDB.UserID != 7 || fromDB.Name != "mapped" { t.Fatalf("db mapping: %+v %v", fromDB, err) }
	tx, err := db.BeginTx(context.Background(), nil)
	if err != nil { t.Fatal(err) }
	defer tx.Rollback()
	transactional := NewStore(tx).Issues()
	fromTx, err := transactional.Create(IssueCreateInput{Name: "created"}, IssueColumns.UserID.Set(7)).One(context.Background(), transactional.Executor)
	if err != nil || fromTx.ID != 11 || fromTx.UserID != 7 { t.Fatalf("tx mapping: %+v %v", fromTx, err) }
}

type modelDriver struct{}
func (modelDriver) Open(string) (driver.Conn, error) { return &modelConnection{}, nil }

type modelConnection struct{}
func (*modelConnection) Prepare(string) (driver.Stmt, error) { return nil, driver.ErrSkip }
func (*modelConnection) Close() error { return nil }
func (*modelConnection) Begin() (driver.Tx, error) { return modelTransaction{}, nil }
func (*modelConnection) QueryContext(context.Context, string, []driver.NamedValue) (driver.Rows, error) {
	return &modelRows{}, nil
}

type modelTransaction struct{}
func (modelTransaction) Commit() error { return nil }
func (modelTransaction) Rollback() error { return nil }

type modelRows struct{ sent bool }
func (*modelRows) Columns() []string { return []string{"id", "user_id", "name", "note", "published", "created_at"} }
func (*modelRows) Close() error { return nil }
func (rows *modelRows) Next(values []driver.Value) error {
	if rows.sent { return io.EOF }
	rows.sent = true
	copy(values, []driver.Value{int64(11), int64(7), "mapped", nil, false, time.Unix(1, 0)})
	return nil
}
`
