package cli

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"html/template"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing/fstest"

	"github.com/ShanilKoshitha/goforge/view"
)

const generatedViewsPath = "resources/views/views_gen.go"

func prepareProjectViews(ctx context.Context, stdin io.Reader, stdout, stderr io.Writer, processes processRunner) error {
	if err := requireProjectRoot(); err != nil {
		return err
	}
	format, err := projectFormat()
	if err != nil {
		return err
	}
	if format > currentProjectFormat {
		return fmt.Errorf("project format version %d is newer than this CLI supports (format %d); upgrade the GoForge CLI", format, currentProjectFormat)
	}
	if format >= 5 {
		return processes.Run(ctx, stdin, stdout, stderr, "go", "run", "./cmd/views")
	}
	return compileProjectViewsIfPresent(stdout)
}

func runProjectViewCompiler(ctx context.Context, stdin io.Reader, stdout, stderr io.Writer, processes processRunner, check bool) error {
	if err := requireProjectRoot(); err != nil {
		return err
	}
	format, err := projectFormat()
	if err != nil {
		return err
	}
	if format > currentProjectFormat {
		return fmt.Errorf("project format version %d is newer than this CLI supports (format %d); upgrade the GoForge CLI", format, currentProjectFormat)
	}
	if format >= 5 {
		arguments := []string{"run", "./cmd/views"}
		if check {
			arguments = append(arguments, "--check")
		}
		return processes.Run(ctx, stdin, stdout, stderr, "go", arguments...)
	}
	return compileProjectViewsWithCheck(check, stdout)
}

func runLockedProjectViewCompiler(
	ctx context.Context,
	stdin io.Reader,
	stdout, stderr io.Writer,
	processes processRunner,
	check bool,
) (err error) {
	if check {
		return runProjectViewCompiler(ctx, stdin, stdout, stderr, processes, true)
	}
	lock, err := acquireGeneratorLock(ctx)
	if err != nil {
		return err
	}
	defer func() { err = errors.Join(err, lock.Close()) }()
	return runProjectViewCompiler(ctx, stdin, stdout, stderr, processes, false)
}

func compileViewArtifact(files map[string]string) (string, error) {
	return compileViewArtifactWithValidation(files, true)
}

func compileViewArtifactWithValidation(files map[string]string, validate bool) (string, error) {
	const prefix = "resources/views/"
	sources := make(fstest.MapFS)
	for name, content := range files {
		if strings.HasPrefix(name, prefix) && strings.HasSuffix(name, ".forge.html") {
			sources[strings.TrimPrefix(name, prefix)] = &fstest.MapFile{Data: []byte(content)}
		}
	}
	compiled, err := view.CompileForge(sources)
	if err != nil {
		return "", fmt.Errorf("compile generated views: %w", err)
	}
	if validate {
		if _, err := view.ParseCompiled(compiled, template.FuncMap{
			"asset":    func(string) (string, error) { return "/assets/example", nil },
			"headline": strings.TrimSpace,
		}); err != nil {
			return "", fmt.Errorf("validate generated views: %w", err)
		}
	}
	return view.GoSource("views", compiled)
}

func compileProjectViews(stdout io.Writer) error {
	return compileProjectViewsWithCheck(false, stdout)
}

func compileProjectViewsWithCheck(check bool, stdout io.Writer) error {
	if err := requireProjectRoot(); err != nil {
		return err
	}
	if _, err := projectModule(); err != nil {
		return err
	}
	compiled, err := compileLegacyForge(os.DirFS("resources/views"))
	if err != nil {
		return fmt.Errorf("compile project views: %w", err)
	}
	if _, err := view.ParseCompiled(compiled, nil); err != nil {
		return fmt.Errorf("validate project views: %w", err)
	}
	artifact, err := renderLegacyCompiledViews(compiled)
	if err != nil {
		return err
	}
	if current, err := os.ReadFile(filepath.FromSlash(generatedViewsPath)); err == nil && bytes.Equal(current, []byte(artifact)) {
		fmt.Fprintln(stdout, "resources/views/views_gen.go is current")
		return nil
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read generated views: %w", err)
	}
	if check {
		return errors.New("resources/views/views_gen.go is stale; run forge views:compile")
	}
	if err := writeManagedFile(generatedViewsPath, []byte(artifact)); err != nil {
		return fmt.Errorf("write generated views: %w", err)
	}
	fmt.Fprintln(stdout, "updated resources/views/views_gen.go")
	return nil
}

func renderLegacyCompiledViews(compiled []view.CompiledTemplate) (string, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by GoForge. DO NOT EDIT.\n\npackage views\n\n")
	output.WriteString("import \"github.com/ShanilKoshitha/goforge/view\"\n\n")
	output.WriteString("var Compiled = []view.CompiledTemplate{\n")
	for _, item := range compiled {
		fmt.Fprintf(&output, "\t{Name: %q, Source: %q},\n", item.Name, item.Source)
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return "", fmt.Errorf("format generated views: %w", err)
	}
	return string(formatted), nil
}

func compileProjectViewsIfPresent(stdout io.Writer) error {
	if err := requireProjectRoot(); err != nil {
		return err
	}
	root := "resources/views"
	found := false
	err := fs.WalkDir(os.DirFS(root), ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() && strings.HasSuffix(name, ".forge.html") {
			found = true
		}
		return nil
	})
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect project views: %w", err)
	}
	if !found {
		return nil
	}
	return compileProjectViews(stdout)
}

func compileViewsWithPlanned(planned []plannedFile) (string, error) {
	files := make(map[string]string)
	root := filepath.Join("resources", "views")
	err := filepath.WalkDir(root, func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(name, ".forge.html") {
			return nil
		}
		content, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		files[filepath.ToSlash(name)] = string(content)
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("read project views: %w", err)
	}
	for _, file := range planned {
		name := filepath.ToSlash(file.path)
		if strings.HasPrefix(name, "resources/views/") && strings.HasSuffix(name, ".forge.html") {
			files[name] = file.content
		}
	}
	return compileViewArtifactWithValidation(files, false)
}
