package cli

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestCompileProjectViewsUpdatesManagedArtifact(t *testing.T) {
	root := projectRoot(t)
	directory := filepath.Join(t.TempDir(), "webapp")
	if err := createProject(newOptions{directory: directory, module: "example.com/webapp", replace: root}); err != nil {
		t.Fatal(err)
	}
	t.Chdir(directory)
	page := filepath.Join("resources", "views", "pages", "welcome.forge.html")
	source, err := os.ReadFile(page)
	if err != nil {
		t.Fatal(err)
	}
	updated := strings.Replace(string(source), "@endsection", "<p>Recompiled</p>\n@endsection", 1)
	if err := os.WriteFile(page, []byte(updated), 0o644); err != nil {
		t.Fatal(err)
	}
	var output bytes.Buffer
	if err := Run([]string{"views:compile"}, &output, &output); err != nil {
		t.Fatal(err)
	}
	artifact, err := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(artifact), "Recompiled") || !strings.Contains(output.String(), "updated resources/views/views_gen.go") {
		t.Fatalf("compiled artifact was not updated:\n%s", artifact)
	}
}

func TestCompileProjectViewsKeepsLastGoodArtifactOnFailure(t *testing.T) {
	root := projectRoot(t)
	directory := filepath.Join(t.TempDir(), "webapp")
	if err := createProject(newOptions{directory: directory, module: "example.com/webapp", replace: root}); err != nil {
		t.Fatal(err)
	}
	t.Chdir(directory)
	before, err := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if err != nil {
		t.Fatal(err)
	}
	page := filepath.Join("resources", "views", "pages", "welcome.forge.html")
	if err := os.WriteFile(page, []byte(`@extends("missing")`), 0o644); err != nil {
		t.Fatal(err)
	}
	var output bytes.Buffer
	err = Run([]string{"views:compile"}, &output, &output)
	if err == nil || !strings.Contains(output.String(), "unknown layout") {
		t.Fatalf("expected template error, got %v: %s", err, output.String())
	}
	after, err := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("failed compilation replaced the last good generated artifact")
	}
}

func TestFormatFiveProjectCompilerRecoversMissingAndCorruptArtifacts(t *testing.T) {
	root := projectRoot(t)
	for _, test := range []struct {
		name    string
		prepare func(*testing.T, string)
		read    func(*testing.T, string) []byte
	}{
		{
			name: "missing",
			prepare: func(t *testing.T, path string) {
				if err := os.Remove(path); err != nil {
					t.Fatal(err)
				}
			},
			read: func(t *testing.T, path string) []byte {
				if _, err := os.Stat(path); !os.IsNotExist(err) {
					t.Fatalf("missing artifact was published by --check: %v", err)
				}
				return nil
			},
		},
		{
			name: "syntactically corrupt",
			prepare: func(t *testing.T, path string) {
				if err := os.WriteFile(path, []byte("package views\nvar Compiled = [\n"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			read: func(t *testing.T, path string) []byte {
				contents, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				return contents
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			directory := filepath.Join(t.TempDir(), "webapp")
			if err := createProject(newOptions{directory: directory, module: "example.com/webapp", replace: root}); err != nil {
				t.Fatal(err)
			}
			t.Chdir(directory)
			artifactPath := filepath.FromSlash(generatedViewsPath)
			test.prepare(t, artifactPath)
			before := test.read(t, artifactPath)
			var output bytes.Buffer
			if err := Run([]string{"views:compile", "--check"}, &output, &output); err == nil || !strings.Contains(output.String(), "is stale") {
				t.Fatalf("%s --check = %v:\n%s", test.name, err, output.String())
			}
			if after := test.read(t, artifactPath); !bytes.Equal(before, after) {
				t.Fatalf("%s --check mutated artifact", test.name)
			}
			output.Reset()
			if err := Run([]string{"views:compile"}, &output, &output); err != nil {
				t.Fatalf("recover %s artifact: %v\n%s", test.name, err, output.String())
			}
			recovered, err := os.ReadFile(artifactPath)
			if err != nil {
				t.Fatal(err)
			}
			if bytes.Equal(recovered, before) || !strings.Contains(string(recovered), "Code generated by GoForge") {
				t.Fatalf("%s artifact was not regenerated:\n%s", test.name, recovered)
			}
		})
	}
}

func TestFormatFiveProjectCompilerUsesApplicationFunctionsAndCheckIsNonMutating(t *testing.T) {
	root := projectRoot(t)
	directory := filepath.Join(t.TempDir(), "webapp")
	if err := createProject(newOptions{directory: directory, module: "example.com/webapp", replace: root}); err != nil {
		t.Fatal(err)
	}
	t.Chdir(directory)
	functionsPath := filepath.Join("resources", "views", "viewfuncs", "functions.go")
	functions, err := os.ReadFile(functionsPath)
	if err != nil {
		t.Fatal(err)
	}
	functions = []byte(strings.Replace(string(functions), `"headline": strings.TrimSpace,`, `"decorate": strings.ToUpper,
		"headline": strings.TrimSpace,`, 1))
	if err := os.WriteFile(functionsPath, functions, 0o644); err != nil {
		t.Fatal(err)
	}
	pagePath := filepath.Join("resources", "views", "pages", "welcome.forge.html")
	page, err := os.ReadFile(pagePath)
	if err != nil {
		t.Fatal(err)
	}
	page = []byte(strings.Replace(string(page), `@section("title"){{.Title}}@endsection`, `@section("title"){{decorate .Title}}@endsection`, 1))
	if err := os.WriteFile(pagePath, page, 0o644); err != nil {
		t.Fatal(err)
	}
	before, err := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if err != nil {
		t.Fatal(err)
	}
	var output bytes.Buffer
	if err := Run([]string{"views:compile", "--check"}, &output, &output); err == nil || !strings.Contains(output.String(), "is stale") {
		t.Fatalf("stale check = %v:\n%s", err, output.String())
	}
	afterCheck, _ := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if !bytes.Equal(before, afterCheck) {
		t.Fatal("--check changed the generated artifact")
	}
	output.Reset()
	if err := Run([]string{"views:compile"}, &output, &output); err != nil {
		t.Fatalf("compile with application function: %v\n%s", err, output.String())
	}
	compiled, _ := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if !strings.Contains(string(compiled), "decorate") {
		t.Fatalf("custom function is absent from compiled source:\n%s", compiled)
	}
	info, err := os.Stat(filepath.FromSlash(generatedViewsPath))
	if err != nil {
		t.Fatal(err)
	}
	if runtime.GOOS != "windows" && info.Mode().Perm() != 0o644 {
		t.Fatalf("generated view mode = %o, want 644", info.Mode().Perm())
	}
	output.Reset()
	if err := Run([]string{"views:compile", "--check"}, &output, &output); err != nil || !strings.Contains(output.String(), "is current") {
		t.Fatalf("current check = %v:\n%s", err, output.String())
	}
	output.Reset()
	if err := Run([]string{"make:resource", "Issue"}, &output, &output); err != nil {
		t.Fatalf("resource generation did not use the application function registry: %v\n%s", err, output.String())
	}
	compiled, _ = os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if !strings.Contains(string(compiled), `Name: "pages/issues/index"`) || !strings.Contains(string(compiled), "decorate") {
		t.Fatalf("resource compilation lost generated or custom-function views:\n%s", compiled)
	}

	invalid := strings.Replace(string(page), "decorate", "missingFunction", 1)
	if err := os.WriteFile(pagePath, []byte(invalid), 0o644); err != nil {
		t.Fatal(err)
	}
	output.Reset()
	if err := Run([]string{"views:compile"}, &output, &output); err == nil || !strings.Contains(output.String(), "missingFunction") {
		t.Fatalf("unknown function compile = %v:\n%s", err, output.String())
	}
	afterFailure, _ := os.ReadFile(filepath.FromSlash(generatedViewsPath))
	if !bytes.Equal(compiled, afterFailure) {
		t.Fatal("invalid custom function replaced the last-good artifact")
	}
}

func TestFormatFiveApplicationFunctionsKeepTrustExplicitAndContextual(t *testing.T) {
	root := projectRoot(t)
	directory := filepath.Join(t.TempDir(), "webapp")
	if err := createProject(newOptions{directory: directory, module: "example.com/webapp", replace: root}); err != nil {
		t.Fatal(err)
	}
	functionsPath := filepath.Join(directory, "resources", "views", "viewfuncs", "functions.go")
	functions, err := os.ReadFile(functionsPath)
	if err != nil {
		t.Fatal(err)
	}
	functions = []byte(strings.Replace(string(functions), `"headline": strings.TrimSpace,`, `"headline": strings.TrimSpace,
		"unsafeString": func() string { return "javascript:alert(1)\"><script>alert(2)</script>" },
		"trustedHTML": func() template.HTML { return template.HTML("<strong>trusted</strong>") },`, 1))
	if err := os.WriteFile(functionsPath, functions, 0o644); err != nil {
		t.Fatal(err)
	}
	pagePath := filepath.Join(directory, "resources", "views", "pages", "function-safety.forge.html")
	page := `<p>{{unsafeString}}</p><div data-value="{{unsafeString}}"></div><a href="{{unsafeString}}">bad</a>{{trustedHTML}}`
	if err := os.WriteFile(pagePath, []byte(page), 0o644); err != nil {
		t.Fatal(err)
	}
	testPath := filepath.Join(directory, "resources", "views", "function_safety_test.go")
	testSource := `package views

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestApplicationFunctionSafety(t *testing.T) {
	engine, err := New()
	if err != nil { t.Fatal(err) }
	response := httptest.NewRecorder()
	if err := engine.Render(response, http.StatusOK, "pages/function-safety", struct{}{}); err != nil { t.Fatal(err) }
	body := response.Body.String()
	if strings.Contains(body, "<script>alert(2)</script>") || !strings.Contains(body, "&lt;script&gt;alert(2)&lt;/script&gt;") {
		t.Fatalf("string function bypassed text or attribute escaping: %s", body)
	}
	if !strings.Contains(body, "href=\"#ZgotmplZ\"") {
		t.Fatalf("string function bypassed URL filtering: %s", body)
	}
	if !strings.Contains(body, "<strong>trusted</strong>") {
		t.Fatalf("explicit template.HTML result was not visibly trusted: %s", body)
	}
}
`
	if err := os.WriteFile(testPath, []byte(testSource), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Chdir(directory)
	var output bytes.Buffer
	if err := Run([]string{"views:compile"}, &output, &output); err != nil {
		t.Fatalf("compile application functions: %v\n%s", err, output.String())
	}
	baseEnvironment := append(os.Environ(),
		"GOCACHE="+filepath.Join(root, ".cache", "go-build"),
		"GOMODCACHE="+filepath.Join(root, ".cache", "go-mod"),
		"GOWORK=off",
	)
	if output, err := generatedCommand(directory, baseEnvironment, "go", "test", "./resources/views", "-run", "TestApplicationFunctionSafety", "-count=1"); err != nil {
		t.Fatalf("application function safety: %v\n%s", err, output)
	}
	if !strings.Contains(string(functions), "func() template.HTML") {
		t.Fatal("trusted HTML bypass is not conspicuous in application-owned source")
	}
}

func TestFormatFourFrozenCompilerBuildServeCheckAndLastGood(t *testing.T) {
	root := projectRoot(t)
	directory := t.TempDir()
	files := map[string]string{
		"forge.yaml": "version: 4\n",
		"go.mod":     "module example.com/legacy\n\ngo 1.25.0\n\nrequire github.com/ShanilKoshitha/goforge v0.5.0\n\nreplace github.com/ShanilKoshitha/goforge => " + filepath.ToSlash(root) + "\n",
		filepath.Join("internal", "models", "legacy.go"): `package models

type Legacy struct {
	ID int64 ` + "`forge:\"primary,generated,protected,required\"`" + `
}
`,
		filepath.Join("resources", "views", "layouts", "app.forge.html"):      `<body>@yield("content")</body>`,
		filepath.Join("resources", "views", "partials", "message.forge.html"): `<span>{{.}}</span>`,
		filepath.Join("resources", "views", "pages", "home.forge.html"): `@extends("layouts/app")
@section("content")@csrf|@if(.Ready)|@@|@include("partials/message", .Message)@endsection`,
		filepath.Join("resources", "views", "functions.go"): `package views

import "github.com/ShanilKoshitha/goforge/view"

func New() (*view.Engine, error) { return view.ParseCompiled(Compiled, nil) }
`,
		filepath.Join("cmd", "server", "main.go"): `package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	views "example.com/legacy/resources/views"
)

func main() {
	engine, err := views.New()
	if err != nil { panic(err) }
	response := httptest.NewRecorder()
	data := struct { Ready bool; Message string }{Ready: true, Message: "<safe>"}
	if err := engine.Render(response, http.StatusOK, "pages/home", data); err != nil { panic(err) }
	fmt.Print(response.Body.String())
}
`,
	}
	for name, contents := range files {
		path := filepath.Join(directory, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	t.Chdir(directory)
	var output bytes.Buffer
	if err := Run([]string{"orm:generate"}, &output, &output); err != nil {
		t.Fatalf("format-4 ORM generation: %v\n%s", err, output.String())
	}
	output.Reset()
	if err := Run([]string{"views:compile"}, &output, &output); err != nil {
		t.Fatalf("format-4 compile: %v\n%s", err, output.String())
	}
	artifactPath := filepath.FromSlash(generatedViewsPath)
	artifact, err := os.ReadFile(artifactPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, literal := range []string{"@csrf", "@if(.Ready)", "@@"} {
		if !strings.Contains(string(artifact), literal) {
			t.Fatalf("format-4 compiler reinterpreted literal %q:\n%s", literal, artifact)
		}
	}
	if !strings.Contains(string(artifact), `{{template \"partials/message\" .Message}}`) {
		t.Fatalf("format-4 include was not compiled:\n%s", artifact)
	}
	output.Reset()
	if err := Run([]string{"views:compile", "--check"}, &output, &output); err != nil || !strings.Contains(output.String(), "is current") {
		t.Fatalf("format-4 current check: %v\n%s", err, output.String())
	}
	baseEnvironment := append(os.Environ(),
		"GOCACHE="+filepath.Join(root, ".cache", "go-build"),
		"GOMODCACHE="+filepath.Join(root, ".cache", "go-mod"),
		"GOWORK=off",
	)
	t.Setenv("GOCACHE", filepath.Join(root, ".cache", "go-build"))
	t.Setenv("GOMODCACHE", filepath.Join(root, ".cache", "go-mod"))
	t.Setenv("GOWORK", "off")
	ormBefore, err := os.ReadFile(filepath.FromSlash(generatedORMPath))
	if err != nil {
		t.Fatal(err)
	}
	viewsBefore := append([]byte(nil), artifact...)
	for _, command := range []string{"test", "build"} {
		output.Reset()
		if err := RunContext(context.Background(), []string{command}, nil, &output, &output); err != nil {
			t.Fatalf("format-4 forge %s: %v\n%s", command, err, output.String())
		}
	}
	assertArtifactBytes(t, generatedORMPath, ormBefore)
	assertArtifactBytes(t, generatedViewsPath, viewsBefore)
	if _, err := os.Stat(workflowBuildDestination()); err != nil {
		t.Fatalf("format-4 forge build did not publish server: %v", err)
	}
	if result, err := generatedCommand(directory, baseEnvironment, "go", "build", "./cmd/server"); err != nil {
		t.Fatalf("format-4 application build: %v\n%s", err, result)
	}
	var served bytes.Buffer
	if err := run(context.Background(), []string{"serve"}, nil, &served, &served, execProcessRunner{}); err != nil {
		t.Fatalf("format-4 serve: %v\n%s", err, served.String())
	}
	if body := served.String(); !strings.Contains(body, "@csrf|@if(.Ready)|@@") || !strings.Contains(body, "&lt;safe&gt;") {
		t.Fatalf("format-4 served output changed semantics: %s", body)
	}
	pagePath := filepath.Join("resources", "views", "pages", "home.forge.html")
	if err := os.WriteFile(pagePath, []byte(`{{-- v0.5-only comment must remain invalid v0.4 source --}}`), 0o644); err != nil {
		t.Fatal(err)
	}
	output.Reset()
	if err := Run([]string{"views:compile"}, &output, &output); err == nil {
		t.Fatalf("format-4 compiler unexpectedly consumed Forge comment:\n%s", output.String())
	}
	after, err := os.ReadFile(artifactPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(artifact, after) {
		t.Fatal("invalid format-4 source replaced the last-good artifact")
	}
}
