package view

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
)

// GoSource emits deterministic, gofmt'd application-owned source containing
// compiled views and their source maps.
func GoSource(packageName string, compiled []CompiledTemplate) (string, error) {
	if !validIdentifier(packageName) {
		return "", fmt.Errorf("invalid Go package name %q", packageName)
	}
	if len(compiled) == 0 {
		return "", fmt.Errorf("compiled views are required")
	}
	items := append([]CompiledTemplate(nil), compiled...)
	sort.Slice(items, func(left, right int) bool { return items[left].Name < items[right].Name })
	for index, item := range items {
		if item.Name == "" {
			return "", fmt.Errorf("compiled view name is required")
		}
		if index > 0 && items[index-1].Name == item.Name {
			return "", fmt.Errorf("duplicate compiled view %q", item.Name)
		}
		for _, mapping := range item.Mappings {
			if mapping.Start < 0 || mapping.End < mapping.Start || mapping.End > len(item.Source) || mapping.SourceStart < 0 || mapping.Path == "" || mapping.Line < 1 || mapping.Column < 1 {
				return "", fmt.Errorf("compiled view %q has an invalid source mapping", item.Name)
			}
		}
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by GoForge. DO NOT EDIT.\n\npackage ")
	output.WriteString(packageName)
	output.WriteString("\n\nimport \"github.com/ShanilKoshitha/goforge/view\"\n\n")
	output.WriteString("var Compiled = []view.CompiledTemplate{\n")
	for _, item := range items {
		fmt.Fprintf(&output, "\t{Name: %s, Source: %s", strconv.Quote(item.Name), strconv.Quote(item.Source))
		if len(item.Mappings) > 0 {
			output.WriteString(", Mappings: []view.SourceMapping{\n")
			for _, mapping := range item.Mappings {
				fmt.Fprintf(&output, "\t\t{Start: %d, End: %d, SourceStart: %d, Path: %s, Line: %d, Column: %d", mapping.Start, mapping.End, mapping.SourceStart, strconv.Quote(mapping.Path), mapping.Line, mapping.Column)
				if mapping.Synthetic {
					output.WriteString(", Synthetic: true")
				}
				if len(mapping.Context) > 0 {
					output.WriteString(", Context: []string{")
					for _, context := range mapping.Context {
						fmt.Fprintf(&output, "%s,", strconv.Quote(context))
					}
					output.WriteString("}")
				}
				output.WriteString("},\n")
			}
			output.WriteString("\t}")
		}
		output.WriteString("},\n")
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return "", fmt.Errorf("format compiled views: %w", err)
	}
	return string(formatted), nil
}
